"""Auto-generated by scripts/generate_tests.py. Do not edit by hand."""

import httpx
import pytest

from smartlyq import SmartlyQ


@pytest.fixture()
def client():
    calls = []

    def handler(request: httpx.Request) -> httpx.Response:
        calls.append((request.method, request.url.path))
        return httpx.Response(200, json={"success": True, "data": {}})

    sq = SmartlyQ("sqk_test_xxxxxxxxxxxx", transport=httpx.MockTransport(handler), max_retries=0)
    yield sq, calls
    sq.close()


def test_account_get_me(client):
    sq, calls = client
    sq.account.get_me()
    assert calls[-1] == ("GET", "/v1/me")


def test_account_get_me_usage(client):
    sq, calls = client
    sq.account.get_me_usage()
    assert calls[-1] == ("GET", "/v1/me/usage")


def test_account_get_me_balance(client):
    sq, calls = client
    sq.account.get_me_balance()
    assert calls[-1] == ("GET", "/v1/me/balance")


def test_captain_send_message(client):
    sq, calls = client
    sq.captain.send_message({})
    assert calls[-1] == ("POST", "/v1/captain/messages")


def test_captain_list_conversations(client):
    sq, calls = client
    sq.captain.list_conversations()
    assert calls[-1] == ("GET", "/v1/captain/conversations")


def test_captain_get_conversation(client):
    sq, calls = client
    sq.captain.get_conversation("test-id")
    assert calls[-1] == ("GET", "/v1/captain/conversations/test-id")


def test_analytics_get_overview(client):
    sq, calls = client
    sq.analytics.get_overview()
    assert calls[-1] == ("GET", "/v1/analytics/overview")


def test_analytics_get_posts(client):
    sq, calls = client
    sq.analytics.get_posts()
    assert calls[-1] == ("GET", "/v1/analytics/posts")


def test_analytics_get_account(client):
    sq, calls = client
    sq.analytics.get_account("test-id")
    assert calls[-1] == ("GET", "/v1/analytics/accounts/test-id")


def test_articles_generate(client):
    sq, calls = client
    sq.articles.generate({})
    assert calls[-1] == ("POST", "/v1/articles/generate")


def test_articles_list(client):
    sq, calls = client
    sq.articles.list()
    assert calls[-1] == ("GET", "/v1/articles")


def test_articles_get(client):
    sq, calls = client
    sq.articles.get("test-id")
    assert calls[-1] == ("GET", "/v1/articles/test-id")


def test_articles_delete(client):
    sq, calls = client
    sq.articles.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/articles/test-id")


def test_audio_text_to_speech(client):
    sq, calls = client
    sq.audio.text_to_speech({})
    assert calls[-1] == ("POST", "/v1/audio/text-to-speech")


def test_audio_speech_to_text(client):
    sq, calls = client
    sq.audio.speech_to_text({})
    assert calls[-1] == ("POST", "/v1/audio/speech-to-text")


def test_audio_get(client):
    sq, calls = client
    sq.audio.get("test-id")
    assert calls[-1] == ("GET", "/v1/audio/test-id")


def test_chatbots_list(client):
    sq, calls = client
    sq.chatbots.list()
    assert calls[-1] == ("GET", "/v1/chatbots")


def test_chatbots_create(client):
    sq, calls = client
    sq.chatbots.create({})
    assert calls[-1] == ("POST", "/v1/chatbots")


def test_chatbots_get(client):
    sq, calls = client
    sq.chatbots.get("test-id")
    assert calls[-1] == ("GET", "/v1/chatbots/test-id")


def test_chatbots_update(client):
    sq, calls = client
    sq.chatbots.update("test-id", {})
    assert calls[-1] == ("PATCH", "/v1/chatbots/test-id")


def test_chatbots_delete(client):
    sq, calls = client
    sq.chatbots.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/chatbots/test-id")


def test_chatbots_train(client):
    sq, calls = client
    sq.chatbots.train("test-id")
    assert calls[-1] == ("POST", "/v1/chatbots/test-id/train")


def test_chatbots_get_train_status(client):
    sq, calls = client
    sq.chatbots.get_train_status("test-id")
    assert calls[-1] == ("GET", "/v1/chatbots/test-id/train-status")


def test_chatbots_send_message(client):
    sq, calls = client
    sq.chatbots.send_message("test-id", {})
    assert calls[-1] == ("POST", "/v1/chatbots/test-id/messages")


def test_chatbots_list_conversations(client):
    sq, calls = client
    sq.chatbots.list_conversations("test-id")
    assert calls[-1] == ("GET", "/v1/chatbots/test-id/conversations")


def test_chatbots_get_conversation_messages(client):
    sq, calls = client
    sq.chatbots.get_conversation_messages("test-id", "test-id")
    assert calls[-1] == ("GET", "/v1/chatbots/test-id/conversations/test-id/messages")


def test_comments_list(client):
    sq, calls = client
    sq.comments.list()
    assert calls[-1] == ("GET", "/v1/social/comments")


def test_comments_reply_to(client):
    sq, calls = client
    sq.comments.reply_to("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/comments/test-id/reply")


def test_comments_hide(client):
    sq, calls = client
    sq.comments.hide("test-id")
    assert calls[-1] == ("POST", "/v1/social/comments/test-id/hide")


def test_comments_delete(client):
    sq, calls = client
    sq.comments.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/social/comments/test-id")


def test_content_rewrite(client):
    sq, calls = client
    sq.content.rewrite({})
    assert calls[-1] == ("POST", "/v1/content/rewrite")


def test_content_generate_caption(client):
    sq, calls = client
    sq.content.generate_caption({})
    assert calls[-1] == ("POST", "/v1/content/caption")


def test_contacts_list(client):
    sq, calls = client
    sq.contacts.list()
    assert calls[-1] == ("GET", "/v1/contacts")


def test_contacts_create(client):
    sq, calls = client
    sq.contacts.create({})
    assert calls[-1] == ("POST", "/v1/contacts")


def test_contacts_get(client):
    sq, calls = client
    sq.contacts.get("test-id")
    assert calls[-1] == ("GET", "/v1/contacts/test-id")


def test_contacts_update(client):
    sq, calls = client
    sq.contacts.update("test-id", {})
    assert calls[-1] == ("PATCH", "/v1/contacts/test-id")


def test_contacts_add_tags(client):
    sq, calls = client
    sq.contacts.add_tags("test-id", {})
    assert calls[-1] == ("POST", "/v1/contacts/test-id/tags")


def test_contacts_remove_tags(client):
    sq, calls = client
    sq.contacts.remove_tags("test-id", {})
    assert calls[-1] == ("DELETE", "/v1/contacts/test-id/tags")


def test_contacts_list_notes(client):
    sq, calls = client
    sq.contacts.list_notes("test-id")
    assert calls[-1] == ("GET", "/v1/contacts/test-id/notes")


def test_contacts_add_note(client):
    sq, calls = client
    sq.contacts.add_note("test-id", {})
    assert calls[-1] == ("POST", "/v1/contacts/test-id/notes")


def test_contacts_enroll(client):
    sq, calls = client
    sq.contacts.enroll("test-id", {})
    assert calls[-1] == ("POST", "/v1/contacts/test-id/enroll")


def test_contacts_add_message(client):
    sq, calls = client
    sq.contacts.add_message("test-id", {})
    assert calls[-1] == ("POST", "/v1/contacts/test-id/messages")


def test_custom_fields_list(client):
    sq, calls = client
    sq.custom_fields.list()
    assert calls[-1] == ("GET", "/v1/custom-fields")


def test_custom_fields_create(client):
    sq, calls = client
    sq.custom_fields.create({})
    assert calls[-1] == ("POST", "/v1/custom-fields")


def test_custom_fields_delete(client):
    sq, calls = client
    sq.custom_fields.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/custom-fields/test-id")


def test_opportunities_list_pipelines(client):
    sq, calls = client
    sq.opportunities.list_pipelines()
    assert calls[-1] == ("GET", "/v1/pipelines")


def test_opportunities_create_pipeline(client):
    sq, calls = client
    sq.opportunities.create_pipeline({})
    assert calls[-1] == ("POST", "/v1/pipelines")


def test_opportunities_list(client):
    sq, calls = client
    sq.opportunities.list()
    assert calls[-1] == ("GET", "/v1/opportunities")


def test_opportunities_create(client):
    sq, calls = client
    sq.opportunities.create({})
    assert calls[-1] == ("POST", "/v1/opportunities")


def test_opportunities_get(client):
    sq, calls = client
    sq.opportunities.get("test-id")
    assert calls[-1] == ("GET", "/v1/opportunities/test-id")


def test_opportunities_update(client):
    sq, calls = client
    sq.opportunities.update("test-id", {})
    assert calls[-1] == ("PATCH", "/v1/opportunities/test-id")


def test_opportunities_delete(client):
    sq, calls = client
    sq.opportunities.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/opportunities/test-id")


def test_opportunities_update_status(client):
    sq, calls = client
    sq.opportunities.update_status("test-id", {})
    assert calls[-1] == ("POST", "/v1/opportunities/test-id/status")


def test_messages_list_conversations(client):
    sq, calls = client
    sq.messages.list_conversations()
    assert calls[-1] == ("GET", "/v1/social/conversations")


def test_messages_list(client):
    sq, calls = client
    sq.messages.list("test-id")
    assert calls[-1] == ("GET", "/v1/social/conversations/test-id/messages")


def test_messages_send(client):
    sq, calls = client
    sq.messages.send("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/conversations/test-id/messages")


def test_messages_mark_conversation_read(client):
    sq, calls = client
    sq.messages.mark_conversation_read("test-id")
    assert calls[-1] == ("POST", "/v1/social/conversations/test-id/read")


def test_images_generate(client):
    sq, calls = client
    sq.images.generate({})
    assert calls[-1] == ("POST", "/v1/images/generate")


def test_images_list(client):
    sq, calls = client
    sq.images.list()
    assert calls[-1] == ("GET", "/v1/images")


def test_images_get(client):
    sq, calls = client
    sq.images.get("test-id")
    assert calls[-1] == ("GET", "/v1/images/test-id")


def test_images_delete(client):
    sq, calls = client
    sq.images.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/images/test-id")


def test_jobs_list(client):
    sq, calls = client
    sq.jobs.list()
    assert calls[-1] == ("GET", "/v1/jobs")


def test_jobs_get(client):
    sq, calls = client
    sq.jobs.get("test-id")
    assert calls[-1] == ("GET", "/v1/jobs/test-id")


def test_jobs_cancel(client):
    sq, calls = client
    sq.jobs.cancel("test-id", {})
    assert calls[-1] == ("POST", "/v1/jobs/test-id/cancel")


def test_media_list(client):
    sq, calls = client
    sq.media.list()
    assert calls[-1] == ("GET", "/v1/media")


def test_media_get(client):
    sq, calls = client
    sq.media.get("test-id")
    assert calls[-1] == ("GET", "/v1/media/test-id")


def test_media_delete(client):
    sq, calls = client
    sq.media.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/media/test-id")


def test_media_get_upload_url(client):
    sq, calls = client
    sq.media.get_upload_url({})
    assert calls[-1] == ("POST", "/v1/media/upload-url")


def test_presentations_generate(client):
    sq, calls = client
    sq.presentations.generate({})
    assert calls[-1] == ("POST", "/v1/presentations/generate")


def test_presentations_list(client):
    sq, calls = client
    sq.presentations.list()
    assert calls[-1] == ("GET", "/v1/presentations")


def test_presentations_get(client):
    sq, calls = client
    sq.presentations.get("test-id")
    assert calls[-1] == ("GET", "/v1/presentations/test-id")


def test_presentations_delete(client):
    sq, calls = client
    sq.presentations.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/presentations/test-id")


def test_profiles_list(client):
    sq, calls = client
    sq.profiles.list()
    assert calls[-1] == ("GET", "/v1/profiles")


def test_profiles_create(client):
    sq, calls = client
    sq.profiles.create({})
    assert calls[-1] == ("POST", "/v1/profiles")


def test_profiles_get(client):
    sq, calls = client
    sq.profiles.get("test-id")
    assert calls[-1] == ("GET", "/v1/profiles/test-id")


def test_profiles_delete(client):
    sq, calls = client
    sq.profiles.delete("test-id", {})
    assert calls[-1] == ("DELETE", "/v1/profiles/test-id")


def test_profiles_list_accounts(client):
    sq, calls = client
    sq.profiles.list_accounts("test-id")
    assert calls[-1] == ("GET", "/v1/profiles/test-id/accounts")


def test_profiles_pause(client):
    sq, calls = client
    sq.profiles.pause("test-id")
    assert calls[-1] == ("POST", "/v1/profiles/test-id/pause")


def test_profiles_resume(client):
    sq, calls = client
    sq.profiles.resume("test-id")
    assert calls[-1] == ("POST", "/v1/profiles/test-id/resume")


def test_profiles_create_connect_link(client):
    sq, calls = client
    sq.profiles.create_connect_link("test-id", {})
    assert calls[-1] == ("POST", "/v1/profiles/test-id/connect-link")


def test_profiles_create_connect_url(client):
    sq, calls = client
    sq.profiles.create_connect_url("test-id", "test-id", {})
    assert calls[-1] == ("POST", "/v1/profiles/test-id/connect/test-id")


def test_profiles_get_account_billing(client):
    sq, calls = client
    sq.profiles.get_account_billing()
    assert calls[-1] == ("GET", "/v1/me/account-billing")


def test_seo_keyword_research(client):
    sq, calls = client
    sq.seo.keyword_research({})
    assert calls[-1] == ("POST", "/v1/seo/keyword-research")


def test_seo_serp(client):
    sq, calls = client
    sq.seo.serp({})
    assert calls[-1] == ("POST", "/v1/seo/serp")


def test_seo_keyword_difficulty(client):
    sq, calls = client
    sq.seo.keyword_difficulty({})
    assert calls[-1] == ("POST", "/v1/seo/keyword-difficulty")


def test_seo_ranked_keywords(client):
    sq, calls = client
    sq.seo.ranked_keywords({})
    assert calls[-1] == ("POST", "/v1/seo/ranked-keywords")


def test_seo_domain_overview(client):
    sq, calls = client
    sq.seo.domain_overview({})
    assert calls[-1] == ("POST", "/v1/seo/domain-overview")


def test_seo_competitors(client):
    sq, calls = client
    sq.seo.competitors({})
    assert calls[-1] == ("POST", "/v1/seo/competitors")


def test_seo_backlinks_summary(client):
    sq, calls = client
    sq.seo.backlinks_summary({})
    assert calls[-1] == ("POST", "/v1/seo/backlinks-summary")


def test_seo_audit(client):
    sq, calls = client
    sq.seo.audit({})
    assert calls[-1] == ("POST", "/v1/seo/audit")


def test_seo_backlink_prospects(client):
    sq, calls = client
    sq.seo.backlink_prospects({})
    assert calls[-1] == ("POST", "/v1/seo/backlink-prospects")


def test_seo_referring_domains(client):
    sq, calls = client
    sq.seo.referring_domains({})
    assert calls[-1] == ("POST", "/v1/seo/referring-domains")


def test_seo_backlink_anchors(client):
    sq, calls = client
    sq.seo.backlink_anchors({})
    assert calls[-1] == ("POST", "/v1/seo/backlink-anchors")


def test_seo_spam_score(client):
    sq, calls = client
    sq.seo.spam_score({})
    assert calls[-1] == ("POST", "/v1/seo/spam-score")


def test_seo_rank_history(client):
    sq, calls = client
    sq.seo.rank_history({})
    assert calls[-1] == ("POST", "/v1/seo/rank-history")


def test_seo_site_audit(client):
    sq, calls = client
    sq.seo.site_audit({})
    assert calls[-1] == ("POST", "/v1/seo/site-audit")


def test_seo_brand_lookup(client):
    sq, calls = client
    sq.seo.brand_lookup({})
    assert calls[-1] == ("POST", "/v1/seo/brand-lookup")


def test_seo_prompt_explorer(client):
    sq, calls = client
    sq.seo.prompt_explorer({})
    assert calls[-1] == ("POST", "/v1/seo/prompt-explorer")


def test_seo_ai_audit(client):
    sq, calls = client
    sq.seo.ai_audit({})
    assert calls[-1] == ("POST", "/v1/seo/ai-audit")


def test_shorts_generate(client):
    sq, calls = client
    sq.shorts.generate({})
    assert calls[-1] == ("POST", "/v1/shorts/generate")


def test_shorts_list(client):
    sq, calls = client
    sq.shorts.list()
    assert calls[-1] == ("GET", "/v1/shorts")


def test_shorts_get(client):
    sq, calls = client
    sq.shorts.get("test-id")
    assert calls[-1] == ("GET", "/v1/shorts/test-id")


def test_social_list_accounts(client):
    sq, calls = client
    sq.social.list_accounts()
    assert calls[-1] == ("GET", "/v1/social/accounts")


def test_social_list_posts(client):
    sq, calls = client
    sq.social.list_posts()
    assert calls[-1] == ("GET", "/v1/social/posts")


def test_social_create_post(client):
    sq, calls = client
    sq.social.create_post({})
    assert calls[-1] == ("POST", "/v1/social/posts")


def test_social_schedule_post(client):
    sq, calls = client
    sq.social.schedule_post({})
    assert calls[-1] == ("POST", "/v1/social/posts/schedule")


def test_social_get_post(client):
    sq, calls = client
    sq.social.get_post("test-id")
    assert calls[-1] == ("GET", "/v1/social/posts/test-id")


def test_social_update_post(client):
    sq, calls = client
    sq.social.update_post("test-id", {})
    assert calls[-1] == ("PATCH", "/v1/social/posts/test-id")


def test_social_delete_post(client):
    sq, calls = client
    sq.social.delete_post("test-id")
    assert calls[-1] == ("DELETE", "/v1/social/posts/test-id")


def test_social_update_account(client):
    sq, calls = client
    sq.social.update_account("test-id", {})
    assert calls[-1] == ("PATCH", "/v1/social/accounts/test-id")


def test_social_get_account_health(client):
    sq, calls = client
    sq.social.get_account_health("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/health")


def test_social_get_account_reconnect_url(client):
    sq, calls = client
    sq.social.get_account_reconnect_url("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/reconnect-url")


def test_social_pause_account(client):
    sq, calls = client
    sq.social.pause_account("test-id")
    assert calls[-1] == ("POST", "/v1/social/accounts/test-id/pause")


def test_social_resume_account(client):
    sq, calls = client
    sq.social.resume_account("test-id")
    assert calls[-1] == ("POST", "/v1/social/accounts/test-id/resume")


def test_social_retry_post(client):
    sq, calls = client
    sq.social.retry_post("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/posts/test-id/retry")


def test_social_connect_account_status(client):
    sq, calls = client
    sq.social.connect_account_status("test-id")
    assert calls[-1] == ("GET", "/v1/social/connect/test-id")


def test_social_connect_account(client):
    sq, calls = client
    sq.social.connect_account("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/connect/test-id")


def test_social_list_queues(client):
    sq, calls = client
    sq.social.list_queues()
    assert calls[-1] == ("GET", "/v1/social/queues")


def test_social_create_queue(client):
    sq, calls = client
    sq.social.create_queue({})
    assert calls[-1] == ("POST", "/v1/social/queues")


def test_social_get_queue(client):
    sq, calls = client
    sq.social.get_queue("test-id")
    assert calls[-1] == ("GET", "/v1/social/queues/test-id")


def test_social_update_queue(client):
    sq, calls = client
    sq.social.update_queue("test-id", {})
    assert calls[-1] == ("PUT", "/v1/social/queues/test-id")


def test_social_delete_queue(client):
    sq, calls = client
    sq.social.delete_queue("test-id")
    assert calls[-1] == ("DELETE", "/v1/social/queues/test-id")


def test_social_get_queue_next_slot(client):
    sq, calls = client
    sq.social.get_queue_next_slot("test-id")
    assert calls[-1] == ("GET", "/v1/social/queues/test-id/next-slot")


def test_social_preview_queue_slots(client):
    sq, calls = client
    sq.social.preview_queue_slots("test-id")
    assert calls[-1] == ("GET", "/v1/social/queues/test-id/preview")


def test_social_unpublish_post(client):
    sq, calls = client
    sq.social.unpublish_post("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/posts/test-id/unpublish")


def test_social_validate_post(client):
    sq, calls = client
    sq.social.validate_post({})
    assert calls[-1] == ("POST", "/v1/social/validate/post")


def test_social_validate_media(client):
    sq, calls = client
    sq.social.validate_media({})
    assert calls[-1] == ("POST", "/v1/social/validate/media")


def test_social_stop_post_recycle(client):
    sq, calls = client
    sq.social.stop_post_recycle("test-id")
    assert calls[-1] == ("DELETE", "/v1/social/posts/test-id/recycle")


def test_social_bulk_schedule_posts(client):
    sq, calls = client
    sq.social.bulk_schedule_posts({})
    assert calls[-1] == ("POST", "/v1/social/posts/bulk")


def test_social_validate_bulk_batch(client):
    sq, calls = client
    sq.social.validate_bulk_batch({})
    assert calls[-1] == ("POST", "/v1/social/posts/bulk/validate")


def test_social_bulk_account_health(client):
    sq, calls = client
    sq.social.bulk_account_health()
    assert calls[-1] == ("GET", "/v1/social/accounts/health")


def test_social_account_follower_stats(client):
    sq, calls = client
    sq.social.account_follower_stats()
    assert calls[-1] == ("GET", "/v1/social/accounts/follower-stats")


def test_social_tiktok_creator_info(client):
    sq, calls = client
    sq.social.tiktok_creator_info("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/tiktok/creator-info")


def test_social_move_account(client):
    sq, calls = client
    sq.social.move_account("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/accounts/test-id/move")


def test_social_list_account_groups(client):
    sq, calls = client
    sq.social.list_account_groups()
    assert calls[-1] == ("GET", "/v1/social/account-groups")


def test_social_create_account_group(client):
    sq, calls = client
    sq.social.create_account_group({})
    assert calls[-1] == ("POST", "/v1/social/account-groups")


def test_social_get_account_group(client):
    sq, calls = client
    sq.social.get_account_group("test-id")
    assert calls[-1] == ("GET", "/v1/social/account-groups/test-id")


def test_social_update_account_group(client):
    sq, calls = client
    sq.social.update_account_group("test-id", {})
    assert calls[-1] == ("PUT", "/v1/social/account-groups/test-id")


def test_social_delete_account_group(client):
    sq, calls = client
    sq.social.delete_account_group("test-id")
    assert calls[-1] == ("DELETE", "/v1/social/account-groups/test-id")


def test_urls_shorten(client):
    sq, calls = client
    sq.urls.shorten({})
    assert calls[-1] == ("POST", "/v1/urls/shorten")


def test_urls_list(client):
    sq, calls = client
    sq.urls.list()
    assert calls[-1] == ("GET", "/v1/urls")


def test_urls_get(client):
    sq, calls = client
    sq.urls.get("test-id")
    assert calls[-1] == ("GET", "/v1/urls/test-id")


def test_urls_delete(client):
    sq, calls = client
    sq.urls.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/urls/test-id")


def test_urls_get_stats(client):
    sq, calls = client
    sq.urls.get_stats("test-id")
    assert calls[-1] == ("GET", "/v1/urls/test-id/stats")


def test_videos_list_models(client):
    sq, calls = client
    sq.videos.list_models()
    assert calls[-1] == ("GET", "/v1/videos/models")


def test_videos_generate(client):
    sq, calls = client
    sq.videos.generate({})
    assert calls[-1] == ("POST", "/v1/videos/generate")


def test_videos_list(client):
    sq, calls = client
    sq.videos.list()
    assert calls[-1] == ("GET", "/v1/videos")


def test_videos_get(client):
    sq, calls = client
    sq.videos.get("test-id")
    assert calls[-1] == ("GET", "/v1/videos/test-id")


def test_videos_delete(client):
    sq, calls = client
    sq.videos.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/videos/test-id")


def test_videos_generate_hook(client):
    sq, calls = client
    sq.videos.generate_hook({})
    assert calls[-1] == ("POST", "/v1/videos/hook")


def test_videos_suggest_broll(client):
    sq, calls = client
    sq.videos.suggest_broll({})
    assert calls[-1] == ("POST", "/v1/videos/broll-suggest")


def test_videos_suggest_emphasis(client):
    sq, calls = client
    sq.videos.suggest_emphasis({})
    assert calls[-1] == ("POST", "/v1/videos/emphasis")


def test_videos_generate_viral_thumbnail(client):
    sq, calls = client
    sq.videos.generate_viral_thumbnail({})
    assert calls[-1] == ("POST", "/v1/videos/viral-thumbnail")


def test_webhooks_list(client):
    sq, calls = client
    sq.webhooks.list()
    assert calls[-1] == ("GET", "/v1/webhooks")


def test_webhooks_create(client):
    sq, calls = client
    sq.webhooks.create({})
    assert calls[-1] == ("POST", "/v1/webhooks")


def test_webhooks_update(client):
    sq, calls = client
    sq.webhooks.update("test-id", {})
    assert calls[-1] == ("PUT", "/v1/webhooks/test-id")


def test_webhooks_delete(client):
    sq, calls = client
    sq.webhooks.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/webhooks/test-id")


def test_webhooks_list_logs(client):
    sq, calls = client
    sq.webhooks.list_logs()
    assert calls[-1] == ("GET", "/v1/webhooks/logs")


def test_webhooks_test(client):
    sq, calls = client
    sq.webhooks.test("test-id")
    assert calls[-1] == ("POST", "/v1/webhooks/test-id/test")


def test_workspaces_list(client):
    sq, calls = client
    sq.workspaces.list()
    assert calls[-1] == ("GET", "/v1/workspaces")


def test_workspaces_create(client):
    sq, calls = client
    sq.workspaces.create({})
    assert calls[-1] == ("POST", "/v1/workspaces")


def test_workspaces_bulk_action(client):
    sq, calls = client
    sq.workspaces.bulk_action({})
    assert calls[-1] == ("POST", "/v1/workspaces/bulk")


def test_workspaces_get(client):
    sq, calls = client
    sq.workspaces.get("test-id")
    assert calls[-1] == ("GET", "/v1/workspaces/test-id")


def test_workspaces_delete(client):
    sq, calls = client
    sq.workspaces.delete("test-id", {})
    assert calls[-1] == ("DELETE", "/v1/workspaces/test-id")


def test_workspaces_disable_saas(client):
    sq, calls = client
    sq.workspaces.disable_saas("test-id", {})
    assert calls[-1] == ("POST", "/v1/workspaces/test-id/disable-saas")


def test_workspaces_pause(client):
    sq, calls = client
    sq.workspaces.pause("test-id")
    assert calls[-1] == ("POST", "/v1/workspaces/test-id/pause")


def test_workspaces_resume(client):
    sq, calls = client
    sq.workspaces.resume("test-id")
    assert calls[-1] == ("POST", "/v1/workspaces/test-id/resume")


def test_workspaces_get_subscription(client):
    sq, calls = client
    sq.workspaces.get_subscription("test-id")
    assert calls[-1] == ("GET", "/v1/workspaces/test-id/subscription")


def test_workspaces_get_wallet(client):
    sq, calls = client
    sq.workspaces.get_wallet("test-id")
    assert calls[-1] == ("GET", "/v1/workspaces/test-id/wallet")


def test_workspaces_list_saas_plans(client):
    sq, calls = client
    sq.workspaces.list_saas_plans()
    assert calls[-1] == ("GET", "/v1/saas/plans")


def test_workspaces_get_saas_plan(client):
    sq, calls = client
    sq.workspaces.get_saas_plan("test-id")
    assert calls[-1] == ("GET", "/v1/saas/plans/test-id")

