"""Auto-generated by scripts/generate_tests.py. Do not edit by hand."""

import httpx
import pytest

from smartlyq import SmartlyQ


@pytest.fixture()
def client():
    calls = []

    def handler(request: httpx.Request) -> httpx.Response:
        calls.append((request.method, request.url.path))
        return httpx.Response(200, json={"success": True, "data": {}})

    sq = SmartlyQ("sqk_test_xxxxxxxxxxxx", transport=httpx.MockTransport(handler), max_retries=0)
    yield sq, calls
    sq.close()


def test_account_get_me(client):
    sq, calls = client
    sq.account.get_me()
    assert calls[-1] == ("GET", "/v1/me")


def test_account_get_me_usage(client):
    sq, calls = client
    sq.account.get_me_usage()
    assert calls[-1] == ("GET", "/v1/me/usage")


def test_account_get_me_balance(client):
    sq, calls = client
    sq.account.get_me_balance()
    assert calls[-1] == ("GET", "/v1/me/balance")


def test_account_get_billing(client):
    sq, calls = client
    sq.account.get_billing()
    assert calls[-1] == ("GET", "/v1/me/billing")


def test_captain_send_message(client):
    sq, calls = client
    sq.captain.send_message({})
    assert calls[-1] == ("POST", "/v1/captain/messages")


def test_captain_list_conversations(client):
    sq, calls = client
    sq.captain.list_conversations()
    assert calls[-1] == ("GET", "/v1/captain/conversations")


def test_captain_get_conversation(client):
    sq, calls = client
    sq.captain.get_conversation("test-id")
    assert calls[-1] == ("GET", "/v1/captain/conversations/test-id")


def test_analytics_get_overview(client):
    sq, calls = client
    sq.analytics.get_overview()
    assert calls[-1] == ("GET", "/v1/analytics/overview")


def test_analytics_get_posts(client):
    sq, calls = client
    sq.analytics.get_posts()
    assert calls[-1] == ("GET", "/v1/analytics/posts")


def test_analytics_get_account(client):
    sq, calls = client
    sq.analytics.get_account("test-id")
    assert calls[-1] == ("GET", "/v1/analytics/accounts/test-id")


def test_analytics_daily_metrics(client):
    sq, calls = client
    sq.analytics.daily_metrics()
    assert calls[-1] == ("GET", "/v1/analytics/daily-metrics")


def test_analytics_best_time(client):
    sq, calls = client
    sq.analytics.best_time()
    assert calls[-1] == ("GET", "/v1/analytics/best-time")


def test_analytics_content_decay(client):
    sq, calls = client
    sq.analytics.content_decay()
    assert calls[-1] == ("GET", "/v1/analytics/content-decay")


def test_analytics_posting_frequency(client):
    sq, calls = client
    sq.analytics.posting_frequency()
    assert calls[-1] == ("GET", "/v1/analytics/posting-frequency")


def test_analytics_post_timeline(client):
    sq, calls = client
    sq.analytics.post_timeline("test-id")
    assert calls[-1] == ("GET", "/v1/analytics/posts/test-id/timeline")


def test_analytics_inbox_volume(client):
    sq, calls = client
    sq.analytics.inbox_volume()
    assert calls[-1] == ("GET", "/v1/analytics/inbox/volume")


def test_analytics_inbox_heatmap(client):
    sq, calls = client
    sq.analytics.inbox_heatmap()
    assert calls[-1] == ("GET", "/v1/analytics/inbox/heatmap")


def test_analytics_inbox_source_breakdown(client):
    sq, calls = client
    sq.analytics.inbox_source_breakdown()
    assert calls[-1] == ("GET", "/v1/analytics/inbox/source-breakdown")


def test_analytics_inbox_response_time(client):
    sq, calls = client
    sq.analytics.inbox_response_time()
    assert calls[-1] == ("GET", "/v1/analytics/inbox/response-time")


def test_analytics_inbox_top_accounts(client):
    sq, calls = client
    sq.analytics.inbox_top_accounts()
    assert calls[-1] == ("GET", "/v1/analytics/inbox/top-accounts")


def test_analytics_inbox_conversations(client):
    sq, calls = client
    sq.analytics.inbox_conversations()
    assert calls[-1] == ("GET", "/v1/analytics/inbox/conversations")


def test_analytics_inbox_conversation_detail(client):
    sq, calls = client
    sq.analytics.inbox_conversation_detail("test-id")
    assert calls[-1] == ("GET", "/v1/analytics/inbox/conversations/test-id")


def test_analytics_get_youtube_channel_insights(client):
    sq, calls = client
    sq.analytics.get_youtube_channel_insights()
    assert calls[-1] == ("GET", "/v1/analytics/youtube/channel-insights")


def test_analytics_get_youtube_daily_views(client):
    sq, calls = client
    sq.analytics.get_youtube_daily_views()
    assert calls[-1] == ("GET", "/v1/analytics/youtube/daily-views")


def test_analytics_get_youtube_video_retention(client):
    sq, calls = client
    sq.analytics.get_youtube_video_retention()
    assert calls[-1] == ("GET", "/v1/analytics/youtube/video-retention")


def test_analytics_get_youtube_demographics(client):
    sq, calls = client
    sq.analytics.get_youtube_demographics()
    assert calls[-1] == ("GET", "/v1/analytics/youtube/demographics")


def test_articles_generate(client):
    sq, calls = client
    sq.articles.generate({})
    assert calls[-1] == ("POST", "/v1/articles/generate")


def test_articles_list(client):
    sq, calls = client
    sq.articles.list()
    assert calls[-1] == ("GET", "/v1/articles")


def test_articles_get(client):
    sq, calls = client
    sq.articles.get("test-id")
    assert calls[-1] == ("GET", "/v1/articles/test-id")


def test_articles_delete(client):
    sq, calls = client
    sq.articles.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/articles/test-id")


def test_audio_text_to_speech(client):
    sq, calls = client
    sq.audio.text_to_speech({})
    assert calls[-1] == ("POST", "/v1/audio/text-to-speech")


def test_audio_speech_to_text(client):
    sq, calls = client
    sq.audio.speech_to_text({})
    assert calls[-1] == ("POST", "/v1/audio/speech-to-text")


def test_audio_get(client):
    sq, calls = client
    sq.audio.get("test-id")
    assert calls[-1] == ("GET", "/v1/audio/test-id")


def test_automations_list(client):
    sq, calls = client
    sq.automations.list()
    assert calls[-1] == ("GET", "/v1/automations")


def test_automations_get(client):
    sq, calls = client
    sq.automations.get("test-id")
    assert calls[-1] == ("GET", "/v1/automations/test-id")


def test_automations_activate(client):
    sq, calls = client
    sq.automations.activate("test-id")
    assert calls[-1] == ("POST", "/v1/automations/test-id/activate")


def test_automations_deactivate(client):
    sq, calls = client
    sq.automations.deactivate("test-id")
    assert calls[-1] == ("POST", "/v1/automations/test-id/deactivate")


def test_automations_trigger(client):
    sq, calls = client
    sq.automations.trigger("test-id", {})
    assert calls[-1] == ("POST", "/v1/automations/test-id/trigger")


def test_automations_list_runs(client):
    sq, calls = client
    sq.automations.list_runs("test-id")
    assert calls[-1] == ("GET", "/v1/automations/test-id/runs")


def test_automations_get_run(client):
    sq, calls = client
    sq.automations.get_run("test-id", "test-id")
    assert calls[-1] == ("GET", "/v1/automations/test-id/runs/test-id")


def test_chatbots_list(client):
    sq, calls = client
    sq.chatbots.list()
    assert calls[-1] == ("GET", "/v1/chatbots")


def test_chatbots_create(client):
    sq, calls = client
    sq.chatbots.create({})
    assert calls[-1] == ("POST", "/v1/chatbots")


def test_chatbots_get(client):
    sq, calls = client
    sq.chatbots.get("test-id")
    assert calls[-1] == ("GET", "/v1/chatbots/test-id")


def test_chatbots_update(client):
    sq, calls = client
    sq.chatbots.update("test-id", {})
    assert calls[-1] == ("PATCH", "/v1/chatbots/test-id")


def test_chatbots_delete(client):
    sq, calls = client
    sq.chatbots.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/chatbots/test-id")


def test_chatbots_train(client):
    sq, calls = client
    sq.chatbots.train("test-id")
    assert calls[-1] == ("POST", "/v1/chatbots/test-id/train")


def test_chatbots_get_train_status(client):
    sq, calls = client
    sq.chatbots.get_train_status("test-id")
    assert calls[-1] == ("GET", "/v1/chatbots/test-id/train-status")


def test_chatbots_send_message(client):
    sq, calls = client
    sq.chatbots.send_message("test-id", {})
    assert calls[-1] == ("POST", "/v1/chatbots/test-id/messages")


def test_chatbots_list_conversations(client):
    sq, calls = client
    sq.chatbots.list_conversations("test-id")
    assert calls[-1] == ("GET", "/v1/chatbots/test-id/conversations")


def test_chatbots_get_conversation_messages(client):
    sq, calls = client
    sq.chatbots.get_conversation_messages("test-id", "test-id")
    assert calls[-1] == ("GET", "/v1/chatbots/test-id/conversations/test-id/messages")


def test_comments_list(client):
    sq, calls = client
    sq.comments.list()
    assert calls[-1] == ("GET", "/v1/social/comments")


def test_comments_reply_to(client):
    sq, calls = client
    sq.comments.reply_to("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/comments/test-id/reply")


def test_comments_hide(client):
    sq, calls = client
    sq.comments.hide("test-id")
    assert calls[-1] == ("POST", "/v1/social/comments/test-id/hide")


def test_comments_delete(client):
    sq, calls = client
    sq.comments.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/social/comments/test-id")


def test_comments_get_post(client):
    sq, calls = client
    sq.comments.get_post("test-id")
    assert calls[-1] == ("GET", "/v1/social/comments/test-id")


def test_content_rewrite(client):
    sq, calls = client
    sq.content.rewrite({})
    assert calls[-1] == ("POST", "/v1/content/rewrite")


def test_content_generate_caption(client):
    sq, calls = client
    sq.content.generate_caption({})
    assert calls[-1] == ("POST", "/v1/content/caption")


def test_crm_delete_contact(client):
    sq, calls = client
    sq.crm.delete_contact("test-id")
    assert calls[-1] == ("DELETE", "/v1/contacts/test-id")


def test_crm_update_custom_field(client):
    sq, calls = client
    sq.crm.update_custom_field("test-id", {})
    assert calls[-1] == ("PATCH", "/v1/custom-fields/test-id")


def test_crm_bulk_import_contacts(client):
    sq, calls = client
    sq.crm.bulk_import_contacts({})
    assert calls[-1] == ("POST", "/v1/contacts/bulk")


def test_crm_contact_channels(client):
    sq, calls = client
    sq.crm.contact_channels("test-id")
    assert calls[-1] == ("GET", "/v1/contacts/test-id/channels")


def test_contacts_list(client):
    sq, calls = client
    sq.contacts.list()
    assert calls[-1] == ("GET", "/v1/contacts")


def test_contacts_create(client):
    sq, calls = client
    sq.contacts.create({})
    assert calls[-1] == ("POST", "/v1/contacts")


def test_contacts_get(client):
    sq, calls = client
    sq.contacts.get("test-id")
    assert calls[-1] == ("GET", "/v1/contacts/test-id")


def test_contacts_update(client):
    sq, calls = client
    sq.contacts.update("test-id", {})
    assert calls[-1] == ("PATCH", "/v1/contacts/test-id")


def test_contacts_add_tags(client):
    sq, calls = client
    sq.contacts.add_tags("test-id", {})
    assert calls[-1] == ("POST", "/v1/contacts/test-id/tags")


def test_contacts_remove_tags(client):
    sq, calls = client
    sq.contacts.remove_tags("test-id", {})
    assert calls[-1] == ("DELETE", "/v1/contacts/test-id/tags")


def test_contacts_list_notes(client):
    sq, calls = client
    sq.contacts.list_notes("test-id")
    assert calls[-1] == ("GET", "/v1/contacts/test-id/notes")


def test_contacts_add_note(client):
    sq, calls = client
    sq.contacts.add_note("test-id", {})
    assert calls[-1] == ("POST", "/v1/contacts/test-id/notes")


def test_contacts_enroll(client):
    sq, calls = client
    sq.contacts.enroll("test-id", {})
    assert calls[-1] == ("POST", "/v1/contacts/test-id/enroll")


def test_contacts_add_message(client):
    sq, calls = client
    sq.contacts.add_message("test-id", {})
    assert calls[-1] == ("POST", "/v1/contacts/test-id/messages")


def test_contacts_set_field(client):
    sq, calls = client
    sq.contacts.set_field("test-id", "test-id", {})
    assert calls[-1] == ("PUT", "/v1/contacts/test-id/fields/test-id")


def test_contacts_clear_field(client):
    sq, calls = client
    sq.contacts.clear_field("test-id", "test-id")
    assert calls[-1] == ("DELETE", "/v1/contacts/test-id/fields/test-id")


def test_custom_fields_list(client):
    sq, calls = client
    sq.custom_fields.list()
    assert calls[-1] == ("GET", "/v1/custom-fields")


def test_custom_fields_create(client):
    sq, calls = client
    sq.custom_fields.create({})
    assert calls[-1] == ("POST", "/v1/custom-fields")


def test_custom_fields_delete(client):
    sq, calls = client
    sq.custom_fields.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/custom-fields/test-id")


def test_opportunities_list_pipelines(client):
    sq, calls = client
    sq.opportunities.list_pipelines()
    assert calls[-1] == ("GET", "/v1/pipelines")


def test_opportunities_create_pipeline(client):
    sq, calls = client
    sq.opportunities.create_pipeline({})
    assert calls[-1] == ("POST", "/v1/pipelines")


def test_opportunities_list(client):
    sq, calls = client
    sq.opportunities.list()
    assert calls[-1] == ("GET", "/v1/opportunities")


def test_opportunities_create(client):
    sq, calls = client
    sq.opportunities.create({})
    assert calls[-1] == ("POST", "/v1/opportunities")


def test_opportunities_get(client):
    sq, calls = client
    sq.opportunities.get("test-id")
    assert calls[-1] == ("GET", "/v1/opportunities/test-id")


def test_opportunities_update(client):
    sq, calls = client
    sq.opportunities.update("test-id", {})
    assert calls[-1] == ("PATCH", "/v1/opportunities/test-id")


def test_opportunities_delete(client):
    sq, calls = client
    sq.opportunities.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/opportunities/test-id")


def test_opportunities_update_status(client):
    sq, calls = client
    sq.opportunities.update_status("test-id", {})
    assert calls[-1] == ("POST", "/v1/opportunities/test-id/status")


def test_messages_list_conversations(client):
    sq, calls = client
    sq.messages.list_conversations()
    assert calls[-1] == ("GET", "/v1/social/conversations")


def test_messages_list(client):
    sq, calls = client
    sq.messages.list("test-id")
    assert calls[-1] == ("GET", "/v1/social/conversations/test-id/messages")


def test_messages_send(client):
    sq, calls = client
    sq.messages.send("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/conversations/test-id/messages")


def test_messages_mark_conversation_read(client):
    sq, calls = client
    sq.messages.mark_conversation_read("test-id")
    assert calls[-1] == ("POST", "/v1/social/conversations/test-id/read")


def test_messages_react_to(client):
    sq, calls = client
    sq.messages.react_to("test-id", "test-id", {})
    assert calls[-1] == ("POST", "/v1/social/conversations/test-id/messages/test-id/reactions")


def test_messages_remove_reaction(client):
    sq, calls = client
    sq.messages.remove_reaction("test-id", "test-id")
    assert calls[-1] == ("DELETE", "/v1/social/conversations/test-id/messages/test-id/reactions")


def test_images_generate(client):
    sq, calls = client
    sq.images.generate({})
    assert calls[-1] == ("POST", "/v1/images/generate")


def test_images_list(client):
    sq, calls = client
    sq.images.list()
    assert calls[-1] == ("GET", "/v1/images")


def test_images_get(client):
    sq, calls = client
    sq.images.get("test-id")
    assert calls[-1] == ("GET", "/v1/images/test-id")


def test_images_delete(client):
    sq, calls = client
    sq.images.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/images/test-id")


def test_jobs_list(client):
    sq, calls = client
    sq.jobs.list()
    assert calls[-1] == ("GET", "/v1/jobs")


def test_jobs_get(client):
    sq, calls = client
    sq.jobs.get("test-id")
    assert calls[-1] == ("GET", "/v1/jobs/test-id")


def test_jobs_cancel(client):
    sq, calls = client
    sq.jobs.cancel("test-id", {})
    assert calls[-1] == ("POST", "/v1/jobs/test-id/cancel")


def test_logs_list(client):
    sq, calls = client
    sq.logs.list()
    assert calls[-1] == ("GET", "/v1/logs")


def test_media_list(client):
    sq, calls = client
    sq.media.list()
    assert calls[-1] == ("GET", "/v1/media")


def test_media_get(client):
    sq, calls = client
    sq.media.get("test-id")
    assert calls[-1] == ("GET", "/v1/media/test-id")


def test_media_delete(client):
    sq, calls = client
    sq.media.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/media/test-id")


def test_media_get_upload_url(client):
    sq, calls = client
    sq.media.get_upload_url({})
    assert calls[-1] == ("POST", "/v1/media/upload-url")


def test_media_upload_direct(client):
    sq, calls = client
    sq.media.upload_direct({})
    assert calls[-1] == ("POST", "/v1/media/upload-direct")


def test_presentations_generate(client):
    sq, calls = client
    sq.presentations.generate({})
    assert calls[-1] == ("POST", "/v1/presentations/generate")


def test_presentations_list(client):
    sq, calls = client
    sq.presentations.list()
    assert calls[-1] == ("GET", "/v1/presentations")


def test_presentations_get(client):
    sq, calls = client
    sq.presentations.get("test-id")
    assert calls[-1] == ("GET", "/v1/presentations/test-id")


def test_presentations_delete(client):
    sq, calls = client
    sq.presentations.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/presentations/test-id")


def test_profiles_list(client):
    sq, calls = client
    sq.profiles.list()
    assert calls[-1] == ("GET", "/v1/profiles")


def test_profiles_create(client):
    sq, calls = client
    sq.profiles.create({})
    assert calls[-1] == ("POST", "/v1/profiles")


def test_profiles_get(client):
    sq, calls = client
    sq.profiles.get("test-id")
    assert calls[-1] == ("GET", "/v1/profiles/test-id")


def test_profiles_update(client):
    sq, calls = client
    sq.profiles.update("test-id", {})
    assert calls[-1] == ("PATCH", "/v1/profiles/test-id")


def test_profiles_delete(client):
    sq, calls = client
    sq.profiles.delete("test-id", {})
    assert calls[-1] == ("DELETE", "/v1/profiles/test-id")


def test_profiles_list_accounts(client):
    sq, calls = client
    sq.profiles.list_accounts("test-id")
    assert calls[-1] == ("GET", "/v1/profiles/test-id/accounts")


def test_profiles_pause(client):
    sq, calls = client
    sq.profiles.pause("test-id")
    assert calls[-1] == ("POST", "/v1/profiles/test-id/pause")


def test_profiles_resume(client):
    sq, calls = client
    sq.profiles.resume("test-id")
    assert calls[-1] == ("POST", "/v1/profiles/test-id/resume")


def test_profiles_create_connect_link(client):
    sq, calls = client
    sq.profiles.create_connect_link("test-id", {})
    assert calls[-1] == ("POST", "/v1/profiles/test-id/connect-link")


def test_profiles_create_connect_url(client):
    sq, calls = client
    sq.profiles.create_connect_url("test-id", "test-id", {})
    assert calls[-1] == ("POST", "/v1/profiles/test-id/connect/test-id")


def test_profiles_get_account_billing(client):
    sq, calls = client
    sq.profiles.get_account_billing()
    assert calls[-1] == ("GET", "/v1/me/account-billing")


def test_reviews_list(client):
    sq, calls = client
    sq.reviews.list()
    assert calls[-1] == ("GET", "/v1/reviews")


def test_reviews_reply_to(client):
    sq, calls = client
    sq.reviews.reply_to("test-id", {})
    assert calls[-1] == ("POST", "/v1/reviews/test-id/reply")


def test_reviews_delete_reply(client):
    sq, calls = client
    sq.reviews.delete_reply("test-id")
    assert calls[-1] == ("DELETE", "/v1/reviews/test-id/reply")


def test_reviews_sync(client):
    sq, calls = client
    sq.reviews.sync({})
    assert calls[-1] == ("POST", "/v1/reviews/sync")


def test_seo_keyword_research(client):
    sq, calls = client
    sq.seo.keyword_research({})
    assert calls[-1] == ("POST", "/v1/seo/keyword-research")


def test_seo_serp(client):
    sq, calls = client
    sq.seo.serp({})
    assert calls[-1] == ("POST", "/v1/seo/serp")


def test_seo_keyword_difficulty(client):
    sq, calls = client
    sq.seo.keyword_difficulty({})
    assert calls[-1] == ("POST", "/v1/seo/keyword-difficulty")


def test_seo_ranked_keywords(client):
    sq, calls = client
    sq.seo.ranked_keywords({})
    assert calls[-1] == ("POST", "/v1/seo/ranked-keywords")


def test_seo_domain_overview(client):
    sq, calls = client
    sq.seo.domain_overview({})
    assert calls[-1] == ("POST", "/v1/seo/domain-overview")


def test_seo_competitors(client):
    sq, calls = client
    sq.seo.competitors({})
    assert calls[-1] == ("POST", "/v1/seo/competitors")


def test_seo_backlinks_summary(client):
    sq, calls = client
    sq.seo.backlinks_summary({})
    assert calls[-1] == ("POST", "/v1/seo/backlinks-summary")


def test_seo_audit(client):
    sq, calls = client
    sq.seo.audit({})
    assert calls[-1] == ("POST", "/v1/seo/audit")


def test_seo_backlink_prospects(client):
    sq, calls = client
    sq.seo.backlink_prospects({})
    assert calls[-1] == ("POST", "/v1/seo/backlink-prospects")


def test_seo_referring_domains(client):
    sq, calls = client
    sq.seo.referring_domains({})
    assert calls[-1] == ("POST", "/v1/seo/referring-domains")


def test_seo_backlink_anchors(client):
    sq, calls = client
    sq.seo.backlink_anchors({})
    assert calls[-1] == ("POST", "/v1/seo/backlink-anchors")


def test_seo_spam_score(client):
    sq, calls = client
    sq.seo.spam_score({})
    assert calls[-1] == ("POST", "/v1/seo/spam-score")


def test_seo_rank_history(client):
    sq, calls = client
    sq.seo.rank_history({})
    assert calls[-1] == ("POST", "/v1/seo/rank-history")


def test_seo_site_audit(client):
    sq, calls = client
    sq.seo.site_audit({})
    assert calls[-1] == ("POST", "/v1/seo/site-audit")


def test_seo_brand_lookup(client):
    sq, calls = client
    sq.seo.brand_lookup({})
    assert calls[-1] == ("POST", "/v1/seo/brand-lookup")


def test_seo_prompt_explorer(client):
    sq, calls = client
    sq.seo.prompt_explorer({})
    assert calls[-1] == ("POST", "/v1/seo/prompt-explorer")


def test_seo_ai_audit(client):
    sq, calls = client
    sq.seo.ai_audit({})
    assert calls[-1] == ("POST", "/v1/seo/ai-audit")


def test_shorts_generate(client):
    sq, calls = client
    sq.shorts.generate({})
    assert calls[-1] == ("POST", "/v1/shorts/generate")


def test_shorts_list(client):
    sq, calls = client
    sq.shorts.list()
    assert calls[-1] == ("GET", "/v1/shorts")


def test_shorts_get(client):
    sq, calls = client
    sq.shorts.get("test-id")
    assert calls[-1] == ("GET", "/v1/shorts/test-id")


def test_social_list_accounts(client):
    sq, calls = client
    sq.social.list_accounts()
    assert calls[-1] == ("GET", "/v1/social/accounts")


def test_social_list_posts(client):
    sq, calls = client
    sq.social.list_posts()
    assert calls[-1] == ("GET", "/v1/social/posts")


def test_social_create_post(client):
    sq, calls = client
    sq.social.create_post({})
    assert calls[-1] == ("POST", "/v1/social/posts")


def test_social_schedule_post(client):
    sq, calls = client
    sq.social.schedule_post({})
    assert calls[-1] == ("POST", "/v1/social/posts/schedule")


def test_social_get_post(client):
    sq, calls = client
    sq.social.get_post("test-id")
    assert calls[-1] == ("GET", "/v1/social/posts/test-id")


def test_social_update_post(client):
    sq, calls = client
    sq.social.update_post("test-id", {})
    assert calls[-1] == ("PATCH", "/v1/social/posts/test-id")


def test_social_delete_post(client):
    sq, calls = client
    sq.social.delete_post("test-id")
    assert calls[-1] == ("DELETE", "/v1/social/posts/test-id")


def test_social_update_account(client):
    sq, calls = client
    sq.social.update_account("test-id", {})
    assert calls[-1] == ("PATCH", "/v1/social/accounts/test-id")


def test_social_disconnect_account(client):
    sq, calls = client
    sq.social.disconnect_account("test-id")
    assert calls[-1] == ("DELETE", "/v1/social/accounts/test-id")


def test_social_get_account_health(client):
    sq, calls = client
    sq.social.get_account_health("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/health")


def test_social_get_account_reconnect_url(client):
    sq, calls = client
    sq.social.get_account_reconnect_url("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/reconnect-url")


def test_social_pause_account(client):
    sq, calls = client
    sq.social.pause_account("test-id")
    assert calls[-1] == ("POST", "/v1/social/accounts/test-id/pause")


def test_social_resume_account(client):
    sq, calls = client
    sq.social.resume_account("test-id")
    assert calls[-1] == ("POST", "/v1/social/accounts/test-id/resume")


def test_social_retry_post(client):
    sq, calls = client
    sq.social.retry_post("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/posts/test-id/retry")


def test_social_connect_account_status(client):
    sq, calls = client
    sq.social.connect_account_status("test-id")
    assert calls[-1] == ("GET", "/v1/social/connect/test-id")


def test_social_connect_account(client):
    sq, calls = client
    sq.social.connect_account("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/connect/test-id")


def test_social_list_queues(client):
    sq, calls = client
    sq.social.list_queues()
    assert calls[-1] == ("GET", "/v1/social/queues")


def test_social_create_queue(client):
    sq, calls = client
    sq.social.create_queue({})
    assert calls[-1] == ("POST", "/v1/social/queues")


def test_social_get_queue(client):
    sq, calls = client
    sq.social.get_queue("test-id")
    assert calls[-1] == ("GET", "/v1/social/queues/test-id")


def test_social_update_queue(client):
    sq, calls = client
    sq.social.update_queue("test-id", {})
    assert calls[-1] == ("PUT", "/v1/social/queues/test-id")


def test_social_delete_queue(client):
    sq, calls = client
    sq.social.delete_queue("test-id")
    assert calls[-1] == ("DELETE", "/v1/social/queues/test-id")


def test_social_get_queue_next_slot(client):
    sq, calls = client
    sq.social.get_queue_next_slot("test-id")
    assert calls[-1] == ("GET", "/v1/social/queues/test-id/next-slot")


def test_social_preview_queue_slots(client):
    sq, calls = client
    sq.social.preview_queue_slots("test-id")
    assert calls[-1] == ("GET", "/v1/social/queues/test-id/preview")


def test_social_unpublish_post(client):
    sq, calls = client
    sq.social.unpublish_post("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/posts/test-id/unpublish")


def test_social_validate_post(client):
    sq, calls = client
    sq.social.validate_post({})
    assert calls[-1] == ("POST", "/v1/social/validate/post")


def test_social_validate_media(client):
    sq, calls = client
    sq.social.validate_media({})
    assert calls[-1] == ("POST", "/v1/social/validate/media")


def test_social_stop_post_recycle(client):
    sq, calls = client
    sq.social.stop_post_recycle("test-id")
    assert calls[-1] == ("DELETE", "/v1/social/posts/test-id/recycle")


def test_social_bulk_schedule_posts(client):
    sq, calls = client
    sq.social.bulk_schedule_posts({})
    assert calls[-1] == ("POST", "/v1/social/posts/bulk")


def test_social_validate_bulk_batch(client):
    sq, calls = client
    sq.social.validate_bulk_batch({})
    assert calls[-1] == ("POST", "/v1/social/posts/bulk/validate")


def test_social_bulk_account_health(client):
    sq, calls = client
    sq.social.bulk_account_health()
    assert calls[-1] == ("GET", "/v1/social/accounts/health")


def test_social_account_follower_stats(client):
    sq, calls = client
    sq.social.account_follower_stats()
    assert calls[-1] == ("GET", "/v1/social/accounts/follower-stats")


def test_social_tiktok_creator_info(client):
    sq, calls = client
    sq.social.tiktok_creator_info("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/tiktok/creator-info")


def test_social_move_account(client):
    sq, calls = client
    sq.social.move_account("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/accounts/test-id/move")


def test_social_list_account_groups(client):
    sq, calls = client
    sq.social.list_account_groups()
    assert calls[-1] == ("GET", "/v1/social/account-groups")


def test_social_create_account_group(client):
    sq, calls = client
    sq.social.create_account_group({})
    assert calls[-1] == ("POST", "/v1/social/account-groups")


def test_social_get_account_group(client):
    sq, calls = client
    sq.social.get_account_group("test-id")
    assert calls[-1] == ("GET", "/v1/social/account-groups/test-id")


def test_social_update_account_group(client):
    sq, calls = client
    sq.social.update_account_group("test-id", {})
    assert calls[-1] == ("PUT", "/v1/social/account-groups/test-id")


def test_social_delete_account_group(client):
    sq, calls = client
    sq.social.delete_account_group("test-id")
    assert calls[-1] == ("DELETE", "/v1/social/account-groups/test-id")


def test_social_get_conversation(client):
    sq, calls = client
    sq.social.get_conversation("test-id")
    assert calls[-1] == ("GET", "/v1/social/conversations/test-id")


def test_social_update_conversation(client):
    sq, calls = client
    sq.social.update_conversation("test-id", {})
    assert calls[-1] == ("PATCH", "/v1/social/conversations/test-id")


def test_social_search_conversations(client):
    sq, calls = client
    sq.social.search_conversations()
    assert calls[-1] == ("GET", "/v1/social/conversations/search")


def test_social_pinterest_boards(client):
    sq, calls = client
    sq.social.pinterest_boards("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/pinterest/boards")


def test_social_youtube_playlists(client):
    sq, calls = client
    sq.social.youtube_playlists("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/youtube/playlists")


def test_social_instagram_publishing_limit(client):
    sq, calls = client
    sq.social.instagram_publishing_limit("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/instagram/publishing-limit")


def test_social_gmb_performance(client):
    sq, calls = client
    sq.social.gmb_performance("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/gmb/performance")


def test_social_gmb_search_keywords(client):
    sq, calls = client
    sq.social.gmb_search_keywords("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/gmb/search-keywords")


def test_social_reddit_search(client):
    sq, calls = client
    sq.social.reddit_search("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/reddit/search")


def test_social_reddit_feed(client):
    sq, calls = client
    sq.social.reddit_feed("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/reddit/feed")


def test_social_reddit_subreddits(client):
    sq, calls = client
    sq.social.reddit_subreddits("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/reddit/subreddits")


def test_social_reddit_subreddit_rules(client):
    sq, calls = client
    sq.social.reddit_subreddit_rules("test-id", "test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/reddit/subreddits/test-id/rules")


def test_social_instagram_stories(client):
    sq, calls = client
    sq.social.instagram_stories("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/instagram/stories")


def test_social_facebook_post_reactions(client):
    sq, calls = client
    sq.social.facebook_post_reactions("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/facebook/post-reactions")


def test_social_instagram_story_insights(client):
    sq, calls = client
    sq.social.instagram_story_insights("test-id", "test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/instagram/stories/test-id/insights")


def test_social_x_retweet(client):
    sq, calls = client
    sq.social.x_retweet("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/accounts/test-id/x/retweets")


def test_social_x_unretweet(client):
    sq, calls = client
    sq.social.x_unretweet("test-id", "test-id")
    assert calls[-1] == ("DELETE", "/v1/social/accounts/test-id/x/retweets/test-id")


def test_social_edit_published_post(client):
    sq, calls = client
    sq.social.edit_published_post("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/posts/test-id/edit")


def test_social_update_post_metadata(client):
    sq, calls = client
    sq.social.update_post_metadata("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/posts/test-id/update-metadata")


def test_social_sync_external_posts(client):
    sq, calls = client
    sq.social.sync_external_posts({})
    assert calls[-1] == ("POST", "/v1/social/posts/sync-external")


def test_social_account_insights(client):
    sq, calls = client
    sq.social.account_insights("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/insights")


def test_social_gmb_locations(client):
    sq, calls = client
    sq.social.gmb_locations("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/gmb/locations")


def test_social_gmb_location(client):
    sq, calls = client
    sq.social.gmb_location("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/gmb/location")


def test_social_gmb_update_location(client):
    sq, calls = client
    sq.social.gmb_update_location("test-id", {})
    assert calls[-1] == ("PATCH", "/v1/social/accounts/test-id/gmb/location")


def test_social_gmb_attributes(client):
    sq, calls = client
    sq.social.gmb_attributes("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/gmb/attributes")


def test_social_gmb_update_attributes(client):
    sq, calls = client
    sq.social.gmb_update_attributes("test-id", {})
    assert calls[-1] == ("PUT", "/v1/social/accounts/test-id/gmb/attributes")


def test_social_gmb_attribute_metadata(client):
    sq, calls = client
    sq.social.gmb_attribute_metadata("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/gmb/attributes/metadata")


def test_social_gmb_media(client):
    sq, calls = client
    sq.social.gmb_media("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/gmb/media")


def test_social_gmb_create_media(client):
    sq, calls = client
    sq.social.gmb_create_media("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/accounts/test-id/gmb/media")


def test_social_gmb_delete_media(client):
    sq, calls = client
    sq.social.gmb_delete_media("test-id", {})
    assert calls[-1] == ("DELETE", "/v1/social/accounts/test-id/gmb/media")


def test_social_gmb_food_menus(client):
    sq, calls = client
    sq.social.gmb_food_menus("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/gmb/food-menus")


def test_social_gmb_update_food_menus(client):
    sq, calls = client
    sq.social.gmb_update_food_menus("test-id", {})
    assert calls[-1] == ("PUT", "/v1/social/accounts/test-id/gmb/food-menus")


def test_social_gmb_place_actions(client):
    sq, calls = client
    sq.social.gmb_place_actions("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/gmb/place-actions")


def test_social_gmb_create_place_action(client):
    sq, calls = client
    sq.social.gmb_create_place_action("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/accounts/test-id/gmb/place-actions")


def test_social_gmb_update_place_action(client):
    sq, calls = client
    sq.social.gmb_update_place_action("test-id", {})
    assert calls[-1] == ("PATCH", "/v1/social/accounts/test-id/gmb/place-actions")


def test_social_gmb_delete_place_action(client):
    sq, calls = client
    sq.social.gmb_delete_place_action("test-id", {})
    assert calls[-1] == ("DELETE", "/v1/social/accounts/test-id/gmb/place-actions")


def test_social_gmb_verifications(client):
    sq, calls = client
    sq.social.gmb_verifications("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/gmb/verifications")


def test_social_gmb_verification_options(client):
    sq, calls = client
    sq.social.gmb_verification_options("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/accounts/test-id/gmb/verifications/options")


def test_social_reddit_subreddit_info(client):
    sq, calls = client
    sq.social.reddit_subreddit_info("test-id", "test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/reddit/subreddits/test-id")


def test_social_x_mentions(client):
    sq, calls = client
    sq.social.x_mentions("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/x/mentions")


def test_social_send_typing_indicator(client):
    sq, calls = client
    sq.social.send_typing_indicator("test-id")
    assert calls[-1] == ("POST", "/v1/social/conversations/test-id/typing")


def test_social_comment_private_reply(client):
    sq, calls = client
    sq.social.comment_private_reply("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/comments/test-id/private-reply")


def test_social_get_messenger_menu(client):
    sq, calls = client
    sq.social.get_messenger_menu("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/messenger/menu")


def test_social_set_messenger_menu(client):
    sq, calls = client
    sq.social.set_messenger_menu("test-id", {})
    assert calls[-1] == ("PUT", "/v1/social/accounts/test-id/messenger/menu")


def test_social_delete_messenger_menu(client):
    sq, calls = client
    sq.social.delete_messenger_menu("test-id")
    assert calls[-1] == ("DELETE", "/v1/social/accounts/test-id/messenger/menu")


def test_social_get_ice_breakers(client):
    sq, calls = client
    sq.social.get_ice_breakers("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/instagram/ice-breakers")


def test_social_set_ice_breakers(client):
    sq, calls = client
    sq.social.set_ice_breakers("test-id", {})
    assert calls[-1] == ("PUT", "/v1/social/accounts/test-id/instagram/ice-breakers")


def test_social_delete_ice_breakers(client):
    sq, calls = client
    sq.social.delete_ice_breakers("test-id")
    assert calls[-1] == ("DELETE", "/v1/social/accounts/test-id/instagram/ice-breakers")


def test_social_facebook_page_insights(client):
    sq, calls = client
    sq.social.facebook_page_insights("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/facebook/page-insights")


def test_social_instagram_audience(client):
    sq, calls = client
    sq.social.instagram_audience("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/instagram/audience")


def test_social_connect_options(client):
    sq, calls = client
    sq.social.connect_options("test-id")
    assert calls[-1] == ("GET", "/v1/social/accounts/test-id/connect-options")


def test_social_connect_select(client):
    sq, calls = client
    sq.social.connect_select("test-id", {})
    assert calls[-1] == ("POST", "/v1/social/accounts/test-id/connect-select")


def test_urls_shorten(client):
    sq, calls = client
    sq.urls.shorten({})
    assert calls[-1] == ("POST", "/v1/urls/shorten")


def test_urls_list(client):
    sq, calls = client
    sq.urls.list()
    assert calls[-1] == ("GET", "/v1/urls")


def test_urls_get(client):
    sq, calls = client
    sq.urls.get("test-id")
    assert calls[-1] == ("GET", "/v1/urls/test-id")


def test_urls_delete(client):
    sq, calls = client
    sq.urls.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/urls/test-id")


def test_urls_get_stats(client):
    sq, calls = client
    sq.urls.get_stats("test-id")
    assert calls[-1] == ("GET", "/v1/urls/test-id/stats")


def test_urls_update_short(client):
    sq, calls = client
    sq.urls.update_short("test-id", {})
    assert calls[-1] == ("PATCH", "/v1/urls/test-id")


def test_videos_list_models(client):
    sq, calls = client
    sq.videos.list_models()
    assert calls[-1] == ("GET", "/v1/videos/models")


def test_videos_generate(client):
    sq, calls = client
    sq.videos.generate({})
    assert calls[-1] == ("POST", "/v1/videos/generate")


def test_videos_list(client):
    sq, calls = client
    sq.videos.list()
    assert calls[-1] == ("GET", "/v1/videos")


def test_videos_get(client):
    sq, calls = client
    sq.videos.get("test-id")
    assert calls[-1] == ("GET", "/v1/videos/test-id")


def test_videos_delete(client):
    sq, calls = client
    sq.videos.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/videos/test-id")


def test_videos_generate_hook(client):
    sq, calls = client
    sq.videos.generate_hook({})
    assert calls[-1] == ("POST", "/v1/videos/hook")


def test_videos_suggest_broll(client):
    sq, calls = client
    sq.videos.suggest_broll({})
    assert calls[-1] == ("POST", "/v1/videos/broll-suggest")


def test_videos_suggest_emphasis(client):
    sq, calls = client
    sq.videos.suggest_emphasis({})
    assert calls[-1] == ("POST", "/v1/videos/emphasis")


def test_videos_generate_viral_thumbnail(client):
    sq, calls = client
    sq.videos.generate_viral_thumbnail({})
    assert calls[-1] == ("POST", "/v1/videos/viral-thumbnail")


def test_webhooks_list(client):
    sq, calls = client
    sq.webhooks.list()
    assert calls[-1] == ("GET", "/v1/webhooks")


def test_webhooks_create(client):
    sq, calls = client
    sq.webhooks.create({})
    assert calls[-1] == ("POST", "/v1/webhooks")


def test_webhooks_update(client):
    sq, calls = client
    sq.webhooks.update("test-id", {})
    assert calls[-1] == ("PUT", "/v1/webhooks/test-id")


def test_webhooks_delete(client):
    sq, calls = client
    sq.webhooks.delete("test-id")
    assert calls[-1] == ("DELETE", "/v1/webhooks/test-id")


def test_webhooks_list_logs(client):
    sq, calls = client
    sq.webhooks.list_logs()
    assert calls[-1] == ("GET", "/v1/webhooks/logs")


def test_webhooks_test(client):
    sq, calls = client
    sq.webhooks.test("test-id")
    assert calls[-1] == ("POST", "/v1/webhooks/test-id/test")


def test_webhooks_replay_delivery(client):
    sq, calls = client
    sq.webhooks.replay_delivery("test-id")
    assert calls[-1] == ("POST", "/v1/webhooks/deliveries/test-id/replay")


def test_whats_app_send_whats_app_message(client):
    sq, calls = client
    sq.whats_app.send_whats_app_message({})
    assert calls[-1] == ("POST", "/v1/whatsapp/messages")


def test_whats_app_list_whats_app_templates(client):
    sq, calls = client
    sq.whats_app.list_whats_app_templates()
    assert calls[-1] == ("GET", "/v1/whatsapp/templates")


def test_whats_app_create_whats_app_template(client):
    sq, calls = client
    sq.whats_app.create_whats_app_template({})
    assert calls[-1] == ("POST", "/v1/whatsapp/templates")


def test_whats_app_get_whats_app_business_profile(client):
    sq, calls = client
    sq.whats_app.get_whats_app_business_profile()
    assert calls[-1] == ("GET", "/v1/whatsapp/business-profile")


def test_whats_app_update_whats_app_business_profile(client):
    sq, calls = client
    sq.whats_app.update_whats_app_business_profile({})
    assert calls[-1] == ("PATCH", "/v1/whatsapp/business-profile")


def test_whats_app_list_whats_app_phone_numbers(client):
    sq, calls = client
    sq.whats_app.list_whats_app_phone_numbers()
    assert calls[-1] == ("GET", "/v1/whatsapp/phone-numbers")


def test_whats_app_get_template(client):
    sq, calls = client
    sq.whats_app.get_template("test-id")
    assert calls[-1] == ("GET", "/v1/whatsapp/templates/test-id")


def test_whats_app_update_template(client):
    sq, calls = client
    sq.whats_app.update_template("test-id", {})
    assert calls[-1] == ("PATCH", "/v1/whatsapp/templates/test-id")


def test_whats_app_delete_template(client):
    sq, calls = client
    sq.whats_app.delete_template("test-id")
    assert calls[-1] == ("DELETE", "/v1/whatsapp/templates/test-id")


def test_whats_app_update_profile_photo(client):
    sq, calls = client
    sq.whats_app.update_profile_photo({})
    assert calls[-1] == ("POST", "/v1/whatsapp/business-profile/photo")


def test_whats_app_get_display_name(client):
    sq, calls = client
    sq.whats_app.get_display_name()
    assert calls[-1] == ("GET", "/v1/whatsapp/business-profile/display-name")


def test_whats_app_update_display_name(client):
    sq, calls = client
    sq.whats_app.update_display_name({})
    assert calls[-1] == ("POST", "/v1/whatsapp/business-profile/display-name")


def test_workspaces_list(client):
    sq, calls = client
    sq.workspaces.list()
    assert calls[-1] == ("GET", "/v1/workspaces")


def test_workspaces_create(client):
    sq, calls = client
    sq.workspaces.create({})
    assert calls[-1] == ("POST", "/v1/workspaces")


def test_workspaces_bulk_action(client):
    sq, calls = client
    sq.workspaces.bulk_action({})
    assert calls[-1] == ("POST", "/v1/workspaces/bulk")


def test_workspaces_get(client):
    sq, calls = client
    sq.workspaces.get("test-id")
    assert calls[-1] == ("GET", "/v1/workspaces/test-id")


def test_workspaces_delete(client):
    sq, calls = client
    sq.workspaces.delete("test-id", {})
    assert calls[-1] == ("DELETE", "/v1/workspaces/test-id")


def test_workspaces_disable_saas(client):
    sq, calls = client
    sq.workspaces.disable_saas("test-id", {})
    assert calls[-1] == ("POST", "/v1/workspaces/test-id/disable-saas")


def test_workspaces_pause(client):
    sq, calls = client
    sq.workspaces.pause("test-id")
    assert calls[-1] == ("POST", "/v1/workspaces/test-id/pause")


def test_workspaces_resume(client):
    sq, calls = client
    sq.workspaces.resume("test-id")
    assert calls[-1] == ("POST", "/v1/workspaces/test-id/resume")


def test_workspaces_get_subscription(client):
    sq, calls = client
    sq.workspaces.get_subscription("test-id")
    assert calls[-1] == ("GET", "/v1/workspaces/test-id/subscription")


def test_workspaces_get_wallet(client):
    sq, calls = client
    sq.workspaces.get_wallet("test-id")
    assert calls[-1] == ("GET", "/v1/workspaces/test-id/wallet")


def test_workspaces_list_saas_plans(client):
    sq, calls = client
    sq.workspaces.list_saas_plans()
    assert calls[-1] == ("GET", "/v1/saas/plans")


def test_workspaces_get_saas_plan(client):
    sq, calls = client
    sq.workspaces.get_saas_plan("test-id")
    assert calls[-1] == ("GET", "/v1/saas/plans/test-id")

