"""Generates smartlyq/resources.py - the resource-based SDK surface - from openapi.json."""

from __future__ import annotations

from model import Method, build_model


def emit_method(m: Method) -> str:
    args = ["self"] + [f"{p}: str" for p in m.path_params]
    if m.has_body:
        args.append("body: dict" if m.body_required else "body: dict | None = None")
    kw = ["*"]
    if m.query_params:
        kw.append("query: dict | None = None")
    kw += [
        "profile_id: str | None = None",
        "idempotency_key: str | None = None",
        "timeout: float | None = None",
    ]
    signature = ", ".join(args + kw)

    if m.path_params:
        path_expr = 'f"' + _fstring_path(m) + '"'
    else:
        path_expr = f'"{m.path}"'

    call_kwargs = []
    if m.has_body:
        call_kwargs.append("body=body")
    if m.query_params:
        call_kwargs.append("query=query")
    call_kwargs += [
        "profile_id=profile_id",
        "idempotency_key=idempotency_key",
        "timeout=timeout",
    ]

    doc = f"{m.summary} `{m.http_method} {m.path}`"
    return "\n".join(
        [
            f"    def {m.name}({signature}) -> Any:",
            f'        """{doc}"""',
            f'        return self._client.request("{m.http_method}", {path_expr}, {", ".join(call_kwargs)})',
        ]
    )


def _fstring_path(m: Method) -> str:
    path = m.path
    for raw, arg in zip(m.raw_path_params, m.path_params):
        path = path.replace("{" + raw + "}", "{quote(" + arg + ", safe='')}")
    return path


def main() -> None:
    resources = build_model()
    blocks = [
        '"""Auto-generated by scripts/generate_client.py. Do not edit by hand."""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "from urllib.parse import quote",
        "",
        "from ._core import CoreClient",
        "",
    ]
    for r in resources:
        blocks.append(f"class {r.class_name}:")
        blocks.append(f'    """{r.tag} endpoints."""')
        blocks.append("")
        blocks.append("    def __init__(self, client: CoreClient):")
        blocks.append("        self._client = client")
        blocks.append("")
        blocks.append("\n\n".join(emit_method(m) for m in r.methods))
        blocks.append("")
        blocks.append("")

    blocks.append("def create_resources(client: CoreClient) -> dict[str, Any]:")
    blocks.append("    return {")
    for r in resources:
        blocks.append(f'        "{r.key}": {r.class_name}(client),')
    blocks.append("    }")
    blocks.append("")

    with open("smartlyq/resources.py", "w") as f:
        f.write("\n".join(blocks))

    count = sum(len(r.methods) for r in resources)
    print(f"Generated smartlyq/resources.py: {len(resources)} resources, {count} methods.")


if __name__ == "__main__":
    main()
