"""Generates tests/test_endpoints_gen.py - one test per SDK method asserting HTTP method + path."""

from __future__ import annotations

from model import Method, Resource, build_model


def emit_test(r: Resource, m: Method) -> str:
    args = ['"test-id"'] * len(m.path_params)
    if m.has_body:
        args.append("{}")
    expected_path = m.path
    for raw in m.raw_path_params:
        expected_path = expected_path.replace("{" + raw + "}", "test-id")
    return "\n".join(
        [
            f"def test_{r.key}_{m.name}(client):",
            f"    sq, calls = client",
            f"    sq.{r.key}.{m.name}({', '.join(args)})",
            f'    assert calls[-1] == ("{m.http_method}", "/v1{expected_path}")',
        ]
    )


def main() -> None:
    resources = build_model()
    blocks = [
        '"""Auto-generated by scripts/generate_tests.py. Do not edit by hand."""',
        "",
        "import httpx",
        "import pytest",
        "",
        "from smartlyq import SmartlyQ",
        "",
        "",
        "@pytest.fixture()",
        "def client():",
        "    calls = []",
        "",
        "    def handler(request: httpx.Request) -> httpx.Response:",
        "        calls.append((request.method, request.url.path))",
        '        return httpx.Response(200, json={"success": True, "data": {}})',
        "",
        '    sq = SmartlyQ("sqk_test_xxxxxxxxxxxx", transport=httpx.MockTransport(handler), max_retries=0)',
        "    yield sq, calls",
        "    sq.close()",
        "",
        "",
    ]
    for r in resources:
        for m in r.methods:
            blocks.append(emit_test(r, m))
            blocks.append("")
            blocks.append("")

    with open("tests/test_endpoints_gen.py", "w") as f:
        f.write("\n".join(blocks))

    count = sum(len(r.methods) for r in resources)
    print(f"Generated tests/test_endpoints_gen.py: {count} endpoint tests.")


if __name__ == "__main__":
    main()
