"""Auto-generated by scripts/generate_client.py. Do not edit by hand."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote

from ._core import CoreClient

class AccountResource:
    """Account endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def get_me(self, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get current user profile `GET /me`"""
        return self._client.request("GET", "/me", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_me_usage(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get usage summary `GET /me/usage`"""
        return self._client.request("GET", "/me/usage", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_me_balance(self, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get wallet balance `GET /me/balance`"""
        return self._client.request("GET", "/me/balance", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class CaptainResource:
    """AI Captain endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def send_message(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Send AI Captain message `POST /captain/messages`"""
        return self._client.request("POST", "/captain/messages", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def list_conversations(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List AI Captain conversations `GET /captain/conversations`"""
        return self._client.request("GET", "/captain/conversations", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_conversation(self, conversation_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get AI Captain conversation `GET /captain/conversations/{conversation_id}`"""
        return self._client.request("GET", f"/captain/conversations/{quote(conversation_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class AnalyticsResource:
    """Analytics endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def get_overview(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get analytics overview `GET /analytics/overview`"""
        return self._client.request("GET", "/analytics/overview", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_posts(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get post analytics `GET /analytics/posts`"""
        return self._client.request("GET", "/analytics/posts", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_account(self, account_id: str, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get account analytics `GET /analytics/accounts/{account_id}`"""
        return self._client.request("GET", f"/analytics/accounts/{quote(account_id, safe='')}", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def daily_metrics(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Daily metrics `GET /analytics/daily-metrics`"""
        return self._client.request("GET", "/analytics/daily-metrics", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def best_time(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Best time to post `GET /analytics/best-time`"""
        return self._client.request("GET", "/analytics/best-time", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def content_decay(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Content decay `GET /analytics/content-decay`"""
        return self._client.request("GET", "/analytics/content-decay", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def posting_frequency(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Posting frequency vs engagement `GET /analytics/posting-frequency`"""
        return self._client.request("GET", "/analytics/posting-frequency", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def post_timeline(self, post_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Post metric timeline `GET /analytics/posts/{post_id}/timeline`"""
        return self._client.request("GET", f"/analytics/posts/{quote(post_id, safe='')}/timeline", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def inbox_volume(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Inbox volume `GET /analytics/inbox/volume`"""
        return self._client.request("GET", "/analytics/inbox/volume", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def inbox_heatmap(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Inbox heatmap `GET /analytics/inbox/heatmap`"""
        return self._client.request("GET", "/analytics/inbox/heatmap", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def inbox_source_breakdown(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Inbox source breakdown `GET /analytics/inbox/source-breakdown`"""
        return self._client.request("GET", "/analytics/inbox/source-breakdown", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def inbox_response_time(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Inbox response time `GET /analytics/inbox/response-time`"""
        return self._client.request("GET", "/analytics/inbox/response-time", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def inbox_top_accounts(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Inbox top accounts `GET /analytics/inbox/top-accounts`"""
        return self._client.request("GET", "/analytics/inbox/top-accounts", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def inbox_conversations(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Inbox conversation stats `GET /analytics/inbox/conversations`"""
        return self._client.request("GET", "/analytics/inbox/conversations", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def inbox_conversation_detail(self, conversation_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Conversation analytics `GET /analytics/inbox/conversations/{conversation_id}`"""
        return self._client.request("GET", f"/analytics/inbox/conversations/{quote(conversation_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class ArticlesResource:
    """Articles endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def generate(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Generate article `POST /articles/generate`"""
        return self._client.request("POST", "/articles/generate", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def list(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List articles `GET /articles`"""
        return self._client.request("GET", "/articles", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get(self, article_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get article `GET /articles/{article_id}`"""
        return self._client.request("GET", f"/articles/{quote(article_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def delete(self, article_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Delete article `DELETE /articles/{article_id}`"""
        return self._client.request("DELETE", f"/articles/{quote(article_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class AudioResource:
    """Audio endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def text_to_speech(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Text to speech `POST /audio/text-to-speech`"""
        return self._client.request("POST", "/audio/text-to-speech", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def speech_to_text(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Speech to text `POST /audio/speech-to-text`"""
        return self._client.request("POST", "/audio/speech-to-text", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get(self, audio_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get audio `GET /audio/{audio_id}`"""
        return self._client.request("GET", f"/audio/{quote(audio_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class AutomationsResource:
    """Automations endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def list(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List automations `GET /automations`"""
        return self._client.request("GET", "/automations", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get(self, automation_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get automation `GET /automations/{automation_id}`"""
        return self._client.request("GET", f"/automations/{quote(automation_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def activate(self, automation_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Activate automation `POST /automations/{automation_id}/activate`"""
        return self._client.request("POST", f"/automations/{quote(automation_id, safe='')}/activate", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def deactivate(self, automation_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Pause automation `POST /automations/{automation_id}/deactivate`"""
        return self._client.request("POST", f"/automations/{quote(automation_id, safe='')}/deactivate", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def trigger(self, automation_id: str, body: dict | None = None, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Trigger automation `POST /automations/{automation_id}/trigger`"""
        return self._client.request("POST", f"/automations/{quote(automation_id, safe='')}/trigger", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def list_runs(self, automation_id: str, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List runs `GET /automations/{automation_id}/runs`"""
        return self._client.request("GET", f"/automations/{quote(automation_id, safe='')}/runs", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_run(self, automation_id: str, run_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get run `GET /automations/{automation_id}/runs/{run_id}`"""
        return self._client.request("GET", f"/automations/{quote(automation_id, safe='')}/runs/{quote(run_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class ChatbotsResource:
    """Chatbot endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def list(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List chatbots `GET /chatbots`"""
        return self._client.request("GET", "/chatbots", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def create(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Create chatbot `POST /chatbots`"""
        return self._client.request("POST", "/chatbots", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get chatbot `GET /chatbots/{id}`"""
        return self._client.request("GET", f"/chatbots/{quote(id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def update(self, id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Update chatbot `PATCH /chatbots/{id}`"""
        return self._client.request("PATCH", f"/chatbots/{quote(id, safe='')}", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def delete(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Delete chatbot `DELETE /chatbots/{id}`"""
        return self._client.request("DELETE", f"/chatbots/{quote(id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def train(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Start chatbot training `POST /chatbots/{id}/train`"""
        return self._client.request("POST", f"/chatbots/{quote(id, safe='')}/train", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_train_status(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get chatbot training status `GET /chatbots/{id}/train-status`"""
        return self._client.request("GET", f"/chatbots/{quote(id, safe='')}/train-status", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def send_message(self, id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Send chatbot message `POST /chatbots/{id}/messages`"""
        return self._client.request("POST", f"/chatbots/{quote(id, safe='')}/messages", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def list_conversations(self, id: str, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List chatbot conversations `GET /chatbots/{id}/conversations`"""
        return self._client.request("GET", f"/chatbots/{quote(id, safe='')}/conversations", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_conversation_messages(self, id: str, conv_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get conversation messages `GET /chatbots/{id}/conversations/{conv_id}/messages`"""
        return self._client.request("GET", f"/chatbots/{quote(id, safe='')}/conversations/{quote(conv_id, safe='')}/messages", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class CommentsResource:
    """Comments endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def list(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List comments `GET /social/comments`"""
        return self._client.request("GET", "/social/comments", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def reply_to(self, comment_id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Reply to a comment `POST /social/comments/{comment_id}/reply`"""
        return self._client.request("POST", f"/social/comments/{quote(comment_id, safe='')}/reply", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def hide(self, comment_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Hide or unhide a comment `POST /social/comments/{comment_id}/hide`"""
        return self._client.request("POST", f"/social/comments/{quote(comment_id, safe='')}/hide", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def delete(self, comment_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Delete a comment `DELETE /social/comments/{comment_id}`"""
        return self._client.request("DELETE", f"/social/comments/{quote(comment_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class ContentResource:
    """Content endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def rewrite(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Rewrite content `POST /content/rewrite`"""
        return self._client.request("POST", "/content/rewrite", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def generate_caption(self, body: dict | None = None, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Generate a social caption `POST /content/caption`"""
        return self._client.request("POST", "/content/caption", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class CrmResource:
    """CRM endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def delete_contact(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Delete contact `DELETE /contacts/{id}`"""
        return self._client.request("DELETE", f"/contacts/{quote(id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def bulk_import_contacts(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Bulk import contacts `POST /contacts/bulk`"""
        return self._client.request("POST", "/contacts/bulk", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class ContactsResource:
    """CRM Contacts endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def list(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List contacts `GET /contacts`"""
        return self._client.request("GET", "/contacts", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def create(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Create or upsert a contact `POST /contacts`"""
        return self._client.request("POST", "/contacts", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get a contact `GET /contacts/{id}`"""
        return self._client.request("GET", f"/contacts/{quote(id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def update(self, id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Update a contact `PATCH /contacts/{id}`"""
        return self._client.request("PATCH", f"/contacts/{quote(id, safe='')}", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def add_tags(self, id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Add tags to a contact `POST /contacts/{id}/tags`"""
        return self._client.request("POST", f"/contacts/{quote(id, safe='')}/tags", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def remove_tags(self, id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Remove tags from a contact `DELETE /contacts/{id}/tags`"""
        return self._client.request("DELETE", f"/contacts/{quote(id, safe='')}/tags", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def list_notes(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List contact notes `GET /contacts/{id}/notes`"""
        return self._client.request("GET", f"/contacts/{quote(id, safe='')}/notes", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def add_note(self, id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Add a note to a contact `POST /contacts/{id}/notes`"""
        return self._client.request("POST", f"/contacts/{quote(id, safe='')}/notes", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def enroll(self, id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Enroll a contact in an automation `POST /contacts/{id}/enroll`"""
        return self._client.request("POST", f"/contacts/{quote(id, safe='')}/enroll", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def add_message(self, id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Log a message on a contact's timeline `POST /contacts/{id}/messages`"""
        return self._client.request("POST", f"/contacts/{quote(id, safe='')}/messages", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class CustomFieldsResource:
    """CRM Custom Fields endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def list(self, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List custom fields `GET /custom-fields`"""
        return self._client.request("GET", "/custom-fields", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def create(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Create a custom field `POST /custom-fields`"""
        return self._client.request("POST", "/custom-fields", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def delete(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Delete a custom field `DELETE /custom-fields/{id}`"""
        return self._client.request("DELETE", f"/custom-fields/{quote(id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class OpportunitiesResource:
    """CRM Opportunities endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def list_pipelines(self, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List pipelines `GET /pipelines`"""
        return self._client.request("GET", "/pipelines", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def create_pipeline(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Create a pipeline `POST /pipelines`"""
        return self._client.request("POST", "/pipelines", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def list(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List opportunities `GET /opportunities`"""
        return self._client.request("GET", "/opportunities", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def create(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Create an opportunity `POST /opportunities`"""
        return self._client.request("POST", "/opportunities", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get an opportunity `GET /opportunities/{id}`"""
        return self._client.request("GET", f"/opportunities/{quote(id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def update(self, id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Update an opportunity `PATCH /opportunities/{id}`"""
        return self._client.request("PATCH", f"/opportunities/{quote(id, safe='')}", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def delete(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Delete an opportunity `DELETE /opportunities/{id}`"""
        return self._client.request("DELETE", f"/opportunities/{quote(id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def update_status(self, id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Update opportunity status `POST /opportunities/{id}/status`"""
        return self._client.request("POST", f"/opportunities/{quote(id, safe='')}/status", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class MessagesResource:
    """Direct Messages endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def list_conversations(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List DM conversations `GET /social/conversations`"""
        return self._client.request("GET", "/social/conversations", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def list(self, conversation_id: str, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List messages in a conversation `GET /social/conversations/{conversation_id}/messages`"""
        return self._client.request("GET", f"/social/conversations/{quote(conversation_id, safe='')}/messages", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def send(self, conversation_id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Send a direct message `POST /social/conversations/{conversation_id}/messages`"""
        return self._client.request("POST", f"/social/conversations/{quote(conversation_id, safe='')}/messages", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def mark_conversation_read(self, conversation_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Mark a conversation read `POST /social/conversations/{conversation_id}/read`"""
        return self._client.request("POST", f"/social/conversations/{quote(conversation_id, safe='')}/read", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class ImagesResource:
    """Images endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def generate(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Generate image `POST /images/generate`"""
        return self._client.request("POST", "/images/generate", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def list(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List images `GET /images`"""
        return self._client.request("GET", "/images", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get(self, image_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get image `GET /images/{image_id}`"""
        return self._client.request("GET", f"/images/{quote(image_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def delete(self, image_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Delete image `DELETE /images/{image_id}`"""
        return self._client.request("DELETE", f"/images/{quote(image_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class JobsResource:
    """Jobs endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def list(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List jobs `GET /jobs`"""
        return self._client.request("GET", "/jobs", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get(self, job_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get job `GET /jobs/{job_id}`"""
        return self._client.request("GET", f"/jobs/{quote(job_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def cancel(self, job_id: str, body: dict | None = None, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Cancel job `POST /jobs/{job_id}/cancel`"""
        return self._client.request("POST", f"/jobs/{quote(job_id, safe='')}/cancel", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class MediaResource:
    """Media endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def list(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List media `GET /media`"""
        return self._client.request("GET", "/media", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get(self, media_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get media `GET /media/{media_id}`"""
        return self._client.request("GET", f"/media/{quote(media_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def delete(self, media_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Delete media `DELETE /media/{media_id}`"""
        return self._client.request("DELETE", f"/media/{quote(media_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_upload_url(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get presigned upload URL `POST /media/upload-url`"""
        return self._client.request("POST", "/media/upload-url", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class PresentationsResource:
    """Presentations endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def generate(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Generate presentation `POST /presentations/generate`"""
        return self._client.request("POST", "/presentations/generate", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def list(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List presentations `GET /presentations`"""
        return self._client.request("GET", "/presentations", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get(self, presentation_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get presentation `GET /presentations/{presentation_id}`"""
        return self._client.request("GET", f"/presentations/{quote(presentation_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def delete(self, presentation_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Delete presentation `DELETE /presentations/{presentation_id}`"""
        return self._client.request("DELETE", f"/presentations/{quote(presentation_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class ProfilesResource:
    """Profiles endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def list(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List profiles `GET /profiles`"""
        return self._client.request("GET", "/profiles", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def create(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Create a profile `POST /profiles`"""
        return self._client.request("POST", "/profiles", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get a profile `GET /profiles/{id}`"""
        return self._client.request("GET", f"/profiles/{quote(id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def delete(self, id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Delete a profile `DELETE /profiles/{id}`"""
        return self._client.request("DELETE", f"/profiles/{quote(id, safe='')}", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def list_accounts(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List a profile's connected accounts `GET /profiles/{id}/accounts`"""
        return self._client.request("GET", f"/profiles/{quote(id, safe='')}/accounts", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def pause(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Pause a profile `POST /profiles/{id}/pause`"""
        return self._client.request("POST", f"/profiles/{quote(id, safe='')}/pause", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def resume(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Resume a profile `POST /profiles/{id}/resume`"""
        return self._client.request("POST", f"/profiles/{quote(id, safe='')}/resume", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def create_connect_link(self, id: str, body: dict | None = None, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Create a hosted connect link `POST /profiles/{id}/connect-link`"""
        return self._client.request("POST", f"/profiles/{quote(id, safe='')}/connect-link", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def create_connect_url(self, id: str, platform: str, body: dict | None = None, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get a raw connect URL for one platform `POST /profiles/{id}/connect/{platform}`"""
        return self._client.request("POST", f"/profiles/{quote(id, safe='')}/connect/{quote(platform, safe='')}", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_account_billing(self, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Account billing summary `GET /me/account-billing`"""
        return self._client.request("GET", "/me/account-billing", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class ReviewsResource:
    """Reviews endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def list(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List reviews `GET /reviews`"""
        return self._client.request("GET", "/reviews", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def reply_to(self, review_id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Reply to review `POST /reviews/{review_id}/reply`"""
        return self._client.request("POST", f"/reviews/{quote(review_id, safe='')}/reply", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def sync(self, body: dict | None = None, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Sync reviews `POST /reviews/sync`"""
        return self._client.request("POST", "/reviews/sync", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class SeoResource:
    """SEO endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def keyword_research(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Keyword research `POST /seo/keyword-research`"""
        return self._client.request("POST", "/seo/keyword-research", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def serp(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Live SERP lookup `POST /seo/serp`"""
        return self._client.request("POST", "/seo/serp", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def keyword_difficulty(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Keyword difficulty `POST /seo/keyword-difficulty`"""
        return self._client.request("POST", "/seo/keyword-difficulty", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def ranked_keywords(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Ranked keywords (rank tracking) `POST /seo/ranked-keywords`"""
        return self._client.request("POST", "/seo/ranked-keywords", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def domain_overview(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Domain rank overview `POST /seo/domain-overview`"""
        return self._client.request("POST", "/seo/domain-overview", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def competitors(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Organic competitors `POST /seo/competitors`"""
        return self._client.request("POST", "/seo/competitors", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def backlinks_summary(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Backlink profile summary `POST /seo/backlinks-summary`"""
        return self._client.request("POST", "/seo/backlinks-summary", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def audit(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """On-page SEO audit `POST /seo/audit`"""
        return self._client.request("POST", "/seo/audit", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def backlink_prospects(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Backlink prospects (link gap) `POST /seo/backlink-prospects`"""
        return self._client.request("POST", "/seo/backlink-prospects", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def referring_domains(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Referring domains `POST /seo/referring-domains`"""
        return self._client.request("POST", "/seo/referring-domains", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def backlink_anchors(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Backlink anchors `POST /seo/backlink-anchors`"""
        return self._client.request("POST", "/seo/backlink-anchors", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def spam_score(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Backlink spam score `POST /seo/spam-score`"""
        return self._client.request("POST", "/seo/spam-score", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def rank_history(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Historical rank overview `POST /seo/rank-history`"""
        return self._client.request("POST", "/seo/rank-history", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def site_audit(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Deep site audit `POST /seo/site-audit`"""
        return self._client.request("POST", "/seo/site-audit", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def brand_lookup(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """AI Visibility: brand lookup `POST /seo/brand-lookup`"""
        return self._client.request("POST", "/seo/brand-lookup", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def prompt_explorer(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """AI Visibility: prompt explorer `POST /seo/prompt-explorer`"""
        return self._client.request("POST", "/seo/prompt-explorer", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def ai_audit(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """AI Visibility Audit (async) `POST /seo/ai-audit`"""
        return self._client.request("POST", "/seo/ai-audit", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class ShortsResource:
    """Shorts endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def generate(self, body: dict | None = None, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Generate viral shorts from a long video `POST /shorts/generate`"""
        return self._client.request("POST", "/shorts/generate", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def list(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List shorts jobs `GET /shorts`"""
        return self._client.request("GET", "/shorts", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get(self, uid: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get shorts job + clips `GET /shorts/{uid}`"""
        return self._client.request("GET", f"/shorts/{quote(uid, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class SocialResource:
    """Social endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def list_accounts(self, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List social accounts `GET /social/accounts`"""
        return self._client.request("GET", "/social/accounts", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def list_posts(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List social posts `GET /social/posts`"""
        return self._client.request("GET", "/social/posts", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def create_post(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Create post (publish immediately) `POST /social/posts`"""
        return self._client.request("POST", "/social/posts", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def schedule_post(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Schedule post `POST /social/posts/schedule`"""
        return self._client.request("POST", "/social/posts/schedule", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_post(self, post_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get social post `GET /social/posts/{post_id}`"""
        return self._client.request("GET", f"/social/posts/{quote(post_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def update_post(self, post_id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Update social post `PATCH /social/posts/{post_id}`"""
        return self._client.request("PATCH", f"/social/posts/{quote(post_id, safe='')}", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def delete_post(self, post_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Delete social post `DELETE /social/posts/{post_id}`"""
        return self._client.request("DELETE", f"/social/posts/{quote(post_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def update_account(self, account_id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Rename account `PATCH /social/accounts/{account_id}`"""
        return self._client.request("PATCH", f"/social/accounts/{quote(account_id, safe='')}", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def disconnect_account(self, account_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Disconnect a social account `DELETE /social/accounts/{account_id}`"""
        return self._client.request("DELETE", f"/social/accounts/{quote(account_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_account_health(self, account_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Account health `GET /social/accounts/{account_id}/health`"""
        return self._client.request("GET", f"/social/accounts/{quote(account_id, safe='')}/health", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_account_reconnect_url(self, account_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Account reconnect URL `GET /social/accounts/{account_id}/reconnect-url`"""
        return self._client.request("GET", f"/social/accounts/{quote(account_id, safe='')}/reconnect-url", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def pause_account(self, account_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Pause posting to an account `POST /social/accounts/{account_id}/pause`"""
        return self._client.request("POST", f"/social/accounts/{quote(account_id, safe='')}/pause", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def resume_account(self, account_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Resume posting to an account `POST /social/accounts/{account_id}/resume`"""
        return self._client.request("POST", f"/social/accounts/{quote(account_id, safe='')}/resume", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def retry_post(self, post_id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Retry publishing a post `POST /social/posts/{post_id}/retry`"""
        return self._client.request("POST", f"/social/posts/{quote(post_id, safe='')}/retry", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def connect_account_status(self, platform: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Poll headless connection status `GET /social/connect/{platform}`"""
        return self._client.request("GET", f"/social/connect/{quote(platform, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def connect_account(self, platform: str, body: dict | None = None, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Start headless account connection `POST /social/connect/{platform}`"""
        return self._client.request("POST", f"/social/connect/{quote(platform, safe='')}", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def list_queues(self, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List queues `GET /social/queues`"""
        return self._client.request("GET", "/social/queues", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def create_queue(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Create queue `POST /social/queues`"""
        return self._client.request("POST", "/social/queues", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_queue(self, queue_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get queue `GET /social/queues/{queue_id}`"""
        return self._client.request("GET", f"/social/queues/{quote(queue_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def update_queue(self, queue_id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Update queue `PUT /social/queues/{queue_id}`"""
        return self._client.request("PUT", f"/social/queues/{quote(queue_id, safe='')}", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def delete_queue(self, queue_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Delete queue `DELETE /social/queues/{queue_id}`"""
        return self._client.request("DELETE", f"/social/queues/{quote(queue_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_queue_next_slot(self, queue_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get next open slot `GET /social/queues/{queue_id}/next-slot`"""
        return self._client.request("GET", f"/social/queues/{quote(queue_id, safe='')}/next-slot", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def preview_queue_slots(self, queue_id: str, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Preview upcoming slots `GET /social/queues/{queue_id}/preview`"""
        return self._client.request("GET", f"/social/queues/{quote(queue_id, safe='')}/preview", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def unpublish_post(self, post_id: str, body: dict | None = None, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Unpublish post `POST /social/posts/{post_id}/unpublish`"""
        return self._client.request("POST", f"/social/posts/{quote(post_id, safe='')}/unpublish", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def validate_post(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Validate post content `POST /social/validate/post`"""
        return self._client.request("POST", "/social/validate/post", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def validate_media(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Validate media URL `POST /social/validate/media`"""
        return self._client.request("POST", "/social/validate/media", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def stop_post_recycle(self, post_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Stop recycling `DELETE /social/posts/{post_id}/recycle`"""
        return self._client.request("DELETE", f"/social/posts/{quote(post_id, safe='')}/recycle", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def bulk_schedule_posts(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Bulk schedule posts `POST /social/posts/bulk`"""
        return self._client.request("POST", "/social/posts/bulk", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def validate_bulk_batch(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Validate a bulk batch `POST /social/posts/bulk/validate`"""
        return self._client.request("POST", "/social/posts/bulk/validate", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def bulk_account_health(self, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Bulk account health `GET /social/accounts/health`"""
        return self._client.request("GET", "/social/accounts/health", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def account_follower_stats(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Follower stats `GET /social/accounts/follower-stats`"""
        return self._client.request("GET", "/social/accounts/follower-stats", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def tiktok_creator_info(self, account_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """TikTok creator info `GET /social/accounts/{account_id}/tiktok/creator-info`"""
        return self._client.request("GET", f"/social/accounts/{quote(account_id, safe='')}/tiktok/creator-info", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def move_account(self, account_id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Move account to profile `POST /social/accounts/{account_id}/move`"""
        return self._client.request("POST", f"/social/accounts/{quote(account_id, safe='')}/move", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def list_account_groups(self, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List account groups `GET /social/account-groups`"""
        return self._client.request("GET", "/social/account-groups", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def create_account_group(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Create account group `POST /social/account-groups`"""
        return self._client.request("POST", "/social/account-groups", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_account_group(self, group_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get account group `GET /social/account-groups/{group_id}`"""
        return self._client.request("GET", f"/social/account-groups/{quote(group_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def update_account_group(self, group_id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Update account group `PUT /social/account-groups/{group_id}`"""
        return self._client.request("PUT", f"/social/account-groups/{quote(group_id, safe='')}", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def delete_account_group(self, group_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Delete account group `DELETE /social/account-groups/{group_id}`"""
        return self._client.request("DELETE", f"/social/account-groups/{quote(group_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_conversation(self, conversation_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get conversation `GET /social/conversations/{conversation_id}`"""
        return self._client.request("GET", f"/social/conversations/{quote(conversation_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def update_conversation(self, conversation_id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Archive / reopen conversation `PATCH /social/conversations/{conversation_id}`"""
        return self._client.request("PATCH", f"/social/conversations/{quote(conversation_id, safe='')}", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def search_conversations(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Search conversations `GET /social/conversations/search`"""
        return self._client.request("GET", "/social/conversations/search", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class UrlsResource:
    """URLs endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def shorten(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Shorten URL `POST /urls/shorten`"""
        return self._client.request("POST", "/urls/shorten", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def list(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List short URLs `GET /urls`"""
        return self._client.request("GET", "/urls", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get(self, url_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get short URL `GET /urls/{url_id}`"""
        return self._client.request("GET", f"/urls/{quote(url_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def delete(self, url_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Delete short URL `DELETE /urls/{url_id}`"""
        return self._client.request("DELETE", f"/urls/{quote(url_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_stats(self, url_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get short URL stats `GET /urls/{url_id}/stats`"""
        return self._client.request("GET", f"/urls/{quote(url_id, safe='')}/stats", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class VideosResource:
    """Videos endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def list_models(self, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List available video models `GET /videos/models`"""
        return self._client.request("GET", "/videos/models", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def generate(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Generate video `POST /videos/generate`"""
        return self._client.request("POST", "/videos/generate", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def list(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List videos `GET /videos`"""
        return self._client.request("GET", "/videos", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get(self, video_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get video `GET /videos/{video_id}`"""
        return self._client.request("GET", f"/videos/{quote(video_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def delete(self, video_id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Delete video `DELETE /videos/{video_id}`"""
        return self._client.request("DELETE", f"/videos/{quote(video_id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def generate_hook(self, body: dict | None = None, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Generate a viral hook line `POST /videos/hook`"""
        return self._client.request("POST", "/videos/hook", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def suggest_broll(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Suggest B-roll moments `POST /videos/broll-suggest`"""
        return self._client.request("POST", "/videos/broll-suggest", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def suggest_emphasis(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Suggest on-screen emphasis `POST /videos/emphasis`"""
        return self._client.request("POST", "/videos/emphasis", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def generate_viral_thumbnail(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Generate a viral thumbnail `POST /videos/viral-thumbnail`"""
        return self._client.request("POST", "/videos/viral-thumbnail", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class WebhooksResource:
    """Webhooks endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def list(self, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List webhooks `GET /webhooks`"""
        return self._client.request("GET", "/webhooks", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def create(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Create webhook `POST /webhooks`"""
        return self._client.request("POST", "/webhooks", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def update(self, id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Update webhook `PUT /webhooks/{id}`"""
        return self._client.request("PUT", f"/webhooks/{quote(id, safe='')}", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def delete(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Delete webhook `DELETE /webhooks/{id}`"""
        return self._client.request("DELETE", f"/webhooks/{quote(id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def list_logs(self, *, query: dict | None = None, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List webhook delivery logs `GET /webhooks/logs`"""
        return self._client.request("GET", "/webhooks/logs", query=query, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def test(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Send test webhook `POST /webhooks/{id}/test`"""
        return self._client.request("POST", f"/webhooks/{quote(id, safe='')}/test", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


class WorkspacesResource:
    """Workspaces endpoints."""

    def __init__(self, client: CoreClient):
        self._client = client

    def list(self, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List workspaces (sub-accounts) `GET /workspaces`"""
        return self._client.request("GET", "/workspaces", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def create(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Create a workspace (sub-account) `POST /workspaces`"""
        return self._client.request("POST", "/workspaces", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def bulk_action(self, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Bulk sub-account action `POST /workspaces/bulk`"""
        return self._client.request("POST", "/workspaces/bulk", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get a workspace (sub-account) `GET /workspaces/{id}`"""
        return self._client.request("GET", f"/workspaces/{quote(id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def delete(self, id: str, body: dict, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Delete a workspace (sub-account) `DELETE /workspaces/{id}`"""
        return self._client.request("DELETE", f"/workspaces/{quote(id, safe='')}", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def disable_saas(self, id: str, body: dict | None = None, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Disable SaaS mode for a workspace `POST /workspaces/{id}/disable-saas`"""
        return self._client.request("POST", f"/workspaces/{quote(id, safe='')}/disable-saas", body=body, profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def pause(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Pause (suspend) a workspace `POST /workspaces/{id}/pause`"""
        return self._client.request("POST", f"/workspaces/{quote(id, safe='')}/pause", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def resume(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Resume a paused workspace `POST /workspaces/{id}/resume`"""
        return self._client.request("POST", f"/workspaces/{quote(id, safe='')}/resume", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_subscription(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get a sub-account's subscription `GET /workspaces/{id}/subscription`"""
        return self._client.request("GET", f"/workspaces/{quote(id, safe='')}/subscription", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_wallet(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get a sub-account's wallet balance `GET /workspaces/{id}/wallet`"""
        return self._client.request("GET", f"/workspaces/{quote(id, safe='')}/wallet", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def list_saas_plans(self, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """List SaaS plans `GET /saas/plans`"""
        return self._client.request("GET", "/saas/plans", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)

    def get_saas_plan(self, id: str, *, profile_id: str | None = None, idempotency_key: str | None = None, timeout: float | None = None) -> Any:
        """Get a SaaS plan `GET /saas/plans/{id}`"""
        return self._client.request("GET", f"/saas/plans/{quote(id, safe='')}", profile_id=profile_id, idempotency_key=idempotency_key, timeout=timeout)


def create_resources(client: CoreClient) -> dict[str, Any]:
    return {
        "account": AccountResource(client),
        "captain": CaptainResource(client),
        "analytics": AnalyticsResource(client),
        "articles": ArticlesResource(client),
        "audio": AudioResource(client),
        "automations": AutomationsResource(client),
        "chatbots": ChatbotsResource(client),
        "comments": CommentsResource(client),
        "content": ContentResource(client),
        "crm": CrmResource(client),
        "contacts": ContactsResource(client),
        "custom_fields": CustomFieldsResource(client),
        "opportunities": OpportunitiesResource(client),
        "messages": MessagesResource(client),
        "images": ImagesResource(client),
        "jobs": JobsResource(client),
        "media": MediaResource(client),
        "presentations": PresentationsResource(client),
        "profiles": ProfilesResource(client),
        "reviews": ReviewsResource(client),
        "seo": SeoResource(client),
        "shorts": ShortsResource(client),
        "social": SocialResource(client),
        "urls": UrlsResource(client),
        "videos": VideosResource(client),
        "webhooks": WebhooksResource(client),
        "workspaces": WorkspacesResource(client),
    }
